package aquino.vladimir.example.xenobladever3;

import android.content.SharedPreferences;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class HiddenQuestPage extends AppCompatActivity {
    public static final String TAG = "HiddenQuestPage";
    ListView hiddenquestLayout;
    List<String> arrayhiddenquestList = new ArrayList<String>();
    HiddenQuestList hiddenQuestList = new HiddenQuestList();
    ArrayAdapter adHQ;


    private boolean boxcheck0;
    private boolean boxcheck1;
    private boolean boxcheck2;
    private boolean boxcheck3;
    private boolean boxcheck4;
    private boolean boxcheck5;
    private boolean boxcheck6;
    private boolean boxcheck7;
    private boolean boxcheck8;
    private boolean boxcheck9;
    private boolean boxcheck10;
    private boolean boxcheck11;
    private boolean boxcheck12;
    private boolean boxcheck13;
    private boolean boxcheck14;
    private boolean boxcheck15;
    private boolean boxcheck16;
    private boolean boxcheck17;
    private boolean boxcheck18;
    private boolean boxcheck19;
    private boolean boxcheck20;
    private boolean boxcheck21;
    private boolean boxcheck22;
    private boolean boxcheck23;
    private boolean boxcheck24;
    private boolean boxcheck25;
    private boolean boxcheck26;
    private boolean boxcheck27;
    private boolean boxcheck28;
    private boolean boxcheck29;
    private boolean boxcheck30;
    private boolean boxcheck31;
    private boolean boxcheck32;
    private boolean boxcheck33;
    private boolean boxcheck34;
    private boolean boxcheck35;
    private boolean boxcheck36;
    private boolean boxcheck37;
    private boolean boxcheck38;
    private boolean boxcheck39;
    private boolean boxcheck40;
    private boolean boxcheck41;
    private boolean boxcheck42;
    private boolean boxcheck43;
    private boolean boxcheck44;
    private boolean boxcheck45;
    private boolean boxcheck46;
    private boolean boxcheck47;
    private boolean boxcheck48;
    private boolean boxcheck49;
    private boolean boxcheck50;
    private boolean boxcheck51;
    private boolean boxcheck52;
    private boolean boxcheck53;
    private boolean boxcheck54;
    private boolean boxcheck55;
    private boolean boxcheck56;
    private boolean boxcheck57;
    private boolean boxcheck58;
    private boolean boxcheck59;
    private boolean boxcheck60;
    private boolean boxcheck61;
    private boolean boxcheck62;
    private boolean boxcheck63;
    private boolean boxcheck64;
    private boolean boxcheck65;
    private boolean boxcheck66;
    private boolean boxcheck67;
    private boolean boxcheck68;
    private boolean boxcheck69;
    private boolean boxcheck70;
    private boolean boxcheck71;
    private boolean boxcheck72;
    private boolean boxcheck73;
    private boolean boxcheck74;
    private boolean boxcheck75;
    private boolean boxcheck76;
    private boolean boxcheck77;
    private boolean boxcheck78;
    private boolean boxcheck79;
    private boolean boxcheck80;
    private boolean boxcheck81;
    private boolean boxcheck82;
    private boolean boxcheck83;
    private boolean boxcheck84;
    private boolean boxcheck85;
    private boolean boxcheck86;
    private boolean boxcheck87;
    private boolean boxcheck88;
    private boolean boxcheck89;
    private boolean boxcheck90;
    private boolean boxcheck91;
    private boolean boxcheck92;
    private boolean boxcheck93;
    private boolean boxcheck94;
    private boolean boxcheck95;
    private boolean boxcheck96;
    private boolean boxcheck97;
    private boolean boxcheck98;
    private boolean boxcheck99;
    private boolean boxcheck100;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_hidden_quest_page);
        hiddenquestLayout = findViewById(R.id.hiddenquestLayout);

        //adapter set
        arrayhiddenquestList = new ArrayList<String>(Arrays.asList(hiddenQuestList.HiddenQuestListBig));


        adHQ = new ArrayAdapter(this, android.R.layout.select_dialog_multichoice, arrayhiddenquestList);
        hiddenquestLayout.setAdapter(adHQ);
        Collections.sort(arrayhiddenquestList);

        adHQ.notifyDataSetChanged();

        hiddenquestLayout.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                int ammount;
                ammount = arrayhiddenquestList.size();
                Toast.makeText(HiddenQuestPage.this, "position" + position + "size" + ammount, Toast.LENGTH_SHORT).show();
                boxcheck0 = hiddenquestLayout.isItemChecked(0);
                boxcheck1 = hiddenquestLayout.isItemChecked(1);
                boxcheck2 = hiddenquestLayout.isItemChecked(2);
                boxcheck3 = hiddenquestLayout.isItemChecked(3);
                boxcheck4 = hiddenquestLayout.isItemChecked(4);
                boxcheck5 = hiddenquestLayout.isItemChecked(5);
                boxcheck6 = hiddenquestLayout.isItemChecked(6);
                boxcheck7 = hiddenquestLayout.isItemChecked(7);
                boxcheck8 = hiddenquestLayout.isItemChecked(8);
                boxcheck9 = hiddenquestLayout.isItemChecked(9);
                boxcheck10 = hiddenquestLayout.isItemChecked(10);
                boxcheck11 = hiddenquestLayout.isItemChecked(11);
                boxcheck12 = hiddenquestLayout.isItemChecked(12);
                boxcheck13 = hiddenquestLayout.isItemChecked(13);
                boxcheck14 = hiddenquestLayout.isItemChecked(14);
                boxcheck15 = hiddenquestLayout.isItemChecked(15);
                boxcheck16 = hiddenquestLayout.isItemChecked(16);
                boxcheck17 = hiddenquestLayout.isItemChecked(17);
                boxcheck18 = hiddenquestLayout.isItemChecked(18);
                boxcheck19 = hiddenquestLayout.isItemChecked(19);
                boxcheck20 = hiddenquestLayout.isItemChecked(20);
                boxcheck21 = hiddenquestLayout.isItemChecked(21);
                boxcheck22 = hiddenquestLayout.isItemChecked(22);
                boxcheck23 = hiddenquestLayout.isItemChecked(23);
                boxcheck24 = hiddenquestLayout.isItemChecked(24);
                boxcheck25 = hiddenquestLayout.isItemChecked(25);
                boxcheck26 = hiddenquestLayout.isItemChecked(26);
                boxcheck27 = hiddenquestLayout.isItemChecked(27);
                boxcheck28 = hiddenquestLayout.isItemChecked(28);
                boxcheck29 = hiddenquestLayout.isItemChecked(29);
                boxcheck30 = hiddenquestLayout.isItemChecked(30);
                boxcheck31 = hiddenquestLayout.isItemChecked(31);
                boxcheck32 = hiddenquestLayout.isItemChecked(32);
                boxcheck33 = hiddenquestLayout.isItemChecked(33);
                boxcheck34 = hiddenquestLayout.isItemChecked(34);
                boxcheck35 = hiddenquestLayout.isItemChecked(35);
                boxcheck36 = hiddenquestLayout.isItemChecked(36);
                boxcheck37 = hiddenquestLayout.isItemChecked(37);
                boxcheck38 = hiddenquestLayout.isItemChecked(38);
                boxcheck39 = hiddenquestLayout.isItemChecked(39);
                boxcheck40 = hiddenquestLayout.isItemChecked(40);
                boxcheck41 = hiddenquestLayout.isItemChecked(41);
                boxcheck42 = hiddenquestLayout.isItemChecked(42);
                boxcheck43 = hiddenquestLayout.isItemChecked(43);
                boxcheck44 = hiddenquestLayout.isItemChecked(44);
                boxcheck45 = hiddenquestLayout.isItemChecked(45);
                boxcheck46 = hiddenquestLayout.isItemChecked(46);
                boxcheck47 = hiddenquestLayout.isItemChecked(47);
                boxcheck48 = hiddenquestLayout.isItemChecked(48);
                boxcheck49 = hiddenquestLayout.isItemChecked(49);
                boxcheck50 = hiddenquestLayout.isItemChecked(50);
                boxcheck51 = hiddenquestLayout.isItemChecked(51);
                boxcheck52 = hiddenquestLayout.isItemChecked(52);
                boxcheck53 = hiddenquestLayout.isItemChecked(53);
                boxcheck54 = hiddenquestLayout.isItemChecked(54);
                boxcheck55 = hiddenquestLayout.isItemChecked(55);
                boxcheck56 = hiddenquestLayout.isItemChecked(56);
                boxcheck57 = hiddenquestLayout.isItemChecked(57);
                boxcheck58 = hiddenquestLayout.isItemChecked(58);
                boxcheck59 = hiddenquestLayout.isItemChecked(59);
                boxcheck60 = hiddenquestLayout.isItemChecked(60);
                boxcheck61 = hiddenquestLayout.isItemChecked(61);
                boxcheck62 = hiddenquestLayout.isItemChecked(62);
                boxcheck63 = hiddenquestLayout.isItemChecked(63);
                boxcheck64 = hiddenquestLayout.isItemChecked(64);
                boxcheck65 = hiddenquestLayout.isItemChecked(65);
                boxcheck66 = hiddenquestLayout.isItemChecked(66);
                boxcheck67 = hiddenquestLayout.isItemChecked(67);
                boxcheck68 = hiddenquestLayout.isItemChecked(68);
                boxcheck69 = hiddenquestLayout.isItemChecked(69);
                boxcheck70 = hiddenquestLayout.isItemChecked(70);
                boxcheck71 = hiddenquestLayout.isItemChecked(71);
                boxcheck72 = hiddenquestLayout.isItemChecked(72);
                boxcheck73 = hiddenquestLayout.isItemChecked(73);
                boxcheck74 = hiddenquestLayout.isItemChecked(74);
                boxcheck75 = hiddenquestLayout.isItemChecked(75);
                boxcheck76 = hiddenquestLayout.isItemChecked(76);
                boxcheck77 = hiddenquestLayout.isItemChecked(77);
                boxcheck78 = hiddenquestLayout.isItemChecked(78);
                boxcheck79 = hiddenquestLayout.isItemChecked(79);
                boxcheck80 = hiddenquestLayout.isItemChecked(80);
                boxcheck81 = hiddenquestLayout.isItemChecked(81);
                boxcheck82 = hiddenquestLayout.isItemChecked(82);
                boxcheck83 = hiddenquestLayout.isItemChecked(83);
                boxcheck84 = hiddenquestLayout.isItemChecked(84);
                boxcheck85 = hiddenquestLayout.isItemChecked(85);
                boxcheck86 = hiddenquestLayout.isItemChecked(86);
                boxcheck87 = hiddenquestLayout.isItemChecked(87);
                boxcheck88 = hiddenquestLayout.isItemChecked(88);
                boxcheck89 = hiddenquestLayout.isItemChecked(89);
                boxcheck90 = hiddenquestLayout.isItemChecked(90);
                boxcheck91 = hiddenquestLayout.isItemChecked(91);
                boxcheck92 = hiddenquestLayout.isItemChecked(92);
                boxcheck93 = hiddenquestLayout.isItemChecked(93);
                boxcheck94 = hiddenquestLayout.isItemChecked(94);
                boxcheck95 = hiddenquestLayout.isItemChecked(95);
                boxcheck96 = hiddenquestLayout.isItemChecked(96);
                boxcheck97 = hiddenquestLayout.isItemChecked(97);
                boxcheck98 = hiddenquestLayout.isItemChecked(98);
                boxcheck99 = hiddenquestLayout.isItemChecked(99);
                boxcheck100 = hiddenquestLayout.isItemChecked(100);

                save();
            }
        });
        load();
        update();
    }

    //save
    private void save() {

        SharedPreferences sharedPreferences = getSharedPreferences("MyData", MODE_PRIVATE);
        SharedPreferences.Editor editor = sharedPreferences.edit();

        editor.putBoolean("name0", boxcheck0);
        editor.putBoolean("name1", boxcheck1);
        editor.putBoolean("name2", boxcheck2);
        editor.putBoolean("name3", boxcheck3);
        editor.putBoolean("name4", boxcheck4);
        editor.putBoolean("name5", boxcheck5);
        editor.putBoolean("name6", boxcheck6);
        editor.putBoolean("name7", boxcheck7);
        editor.putBoolean("name8", boxcheck8);
        editor.putBoolean("name9", boxcheck9);
        editor.putBoolean("name10", boxcheck10);
        editor.putBoolean("name11", boxcheck11);
        editor.putBoolean("name12", boxcheck12);
        editor.putBoolean("name13", boxcheck13);
        editor.putBoolean("name14", boxcheck14);
        editor.putBoolean("name16", boxcheck16);
        editor.putBoolean("name17", boxcheck17);
        editor.putBoolean("name18", boxcheck18);
        editor.putBoolean("name19", boxcheck19);
        editor.putBoolean("name20", boxcheck20);
        editor.putBoolean("name21", boxcheck21);
        editor.putBoolean("name22", boxcheck22);
        editor.putBoolean("name23", boxcheck23);
        editor.putBoolean("name24", boxcheck24);
        editor.putBoolean("name25", boxcheck25);
        editor.putBoolean("name26", boxcheck26);
        editor.putBoolean("name27", boxcheck27);
        editor.putBoolean("name28", boxcheck28);
        editor.putBoolean("name29", boxcheck29);
        editor.putBoolean("name30", boxcheck30);
        editor.putBoolean("name31", boxcheck31);
        editor.putBoolean("name32", boxcheck32);
        editor.putBoolean("name33", boxcheck33);
        editor.putBoolean("name35", boxcheck35);
        editor.putBoolean("name36", boxcheck36);
        editor.putBoolean("name37", boxcheck37);
        editor.putBoolean("name38", boxcheck38);
        editor.putBoolean("name39", boxcheck39);
        editor.putBoolean("name40", boxcheck40);
        editor.putBoolean("name41", boxcheck41);
        editor.putBoolean("name42", boxcheck42);
        editor.putBoolean("name43", boxcheck43);
        editor.putBoolean("name44", boxcheck44);
        editor.putBoolean("name45", boxcheck45);
        editor.putBoolean("name46", boxcheck46);
        editor.putBoolean("name47", boxcheck47);
        editor.putBoolean("name48", boxcheck48);
        editor.putBoolean("name49", boxcheck49);
        editor.putBoolean("name51", boxcheck51);
        editor.putBoolean("name52", boxcheck52);
        editor.putBoolean("name53", boxcheck53);
        editor.putBoolean("name54", boxcheck54);
        editor.putBoolean("name55", boxcheck55);
        editor.putBoolean("name56", boxcheck56);
        editor.putBoolean("name57", boxcheck57);
        editor.putBoolean("name58", boxcheck58);
        editor.putBoolean("name59", boxcheck59);
        editor.putBoolean("name60", boxcheck60);
        editor.putBoolean("name61", boxcheck61);
        editor.putBoolean("name62", boxcheck62);
        editor.putBoolean("name63", boxcheck63);
        editor.putBoolean("name64", boxcheck64);
        editor.putBoolean("name65", boxcheck65);
        editor.putBoolean("name66", boxcheck66);
        editor.putBoolean("name67", boxcheck67);
        editor.putBoolean("name68", boxcheck68);
        editor.putBoolean("name69", boxcheck69);
        editor.putBoolean("name70", boxcheck70);
        editor.putBoolean("name71", boxcheck71);
        editor.putBoolean("name72", boxcheck72);
        editor.putBoolean("name73", boxcheck73);
        editor.putBoolean("name74", boxcheck74);
        editor.putBoolean("name75", boxcheck75);
        editor.putBoolean("name76", boxcheck76);
        editor.putBoolean("name77", boxcheck77);
        editor.putBoolean("name78", boxcheck78);
        editor.putBoolean("name79", boxcheck79);
        editor.putBoolean("name80", boxcheck80);
        editor.putBoolean("name81", boxcheck81);
        editor.putBoolean("name82", boxcheck82);
        editor.putBoolean("name83", boxcheck83);
        editor.putBoolean("name84", boxcheck84);
        editor.putBoolean("name85", boxcheck85);
        editor.putBoolean("name86", boxcheck86);
        editor.putBoolean("name87", boxcheck87);
        editor.putBoolean("name88", boxcheck88);
        editor.putBoolean("name89", boxcheck89);
        editor.putBoolean("name90", boxcheck90);
        editor.putBoolean("name91", boxcheck91);
        editor.putBoolean("name92", boxcheck92);
        editor.putBoolean("name93", boxcheck93);
        editor.putBoolean("name94", boxcheck94);
        editor.putBoolean("name95", boxcheck95);
        editor.putBoolean("name96", boxcheck96);
        editor.putBoolean("name97", boxcheck97);
        editor.putBoolean("name98", boxcheck98);
        editor.putBoolean("name99", boxcheck99);
        editor.putBoolean("name100", boxcheck100);

        editor.commit();

        Log.d(TAG, "save: SAVE");
    }

    //load
    private void load() {
        SharedPreferences sharedPreferences = getSharedPreferences("MyData", MODE_PRIVATE);

        boolean box0 = sharedPreferences.getBoolean("name0", false);
        boolean box1 = sharedPreferences.getBoolean("name1", false);
        boolean box2 = sharedPreferences.getBoolean("name2", false);
        boolean box3 = sharedPreferences.getBoolean("name3", false);
        boolean box4 = sharedPreferences.getBoolean("name4", false);
        boolean box5 = sharedPreferences.getBoolean("name5", false);
        boolean box6 = sharedPreferences.getBoolean("name6", false);
        boolean box7 = sharedPreferences.getBoolean("name7", false);
        boolean box8 = sharedPreferences.getBoolean("name8", false);
        boolean box9 = sharedPreferences.getBoolean("name9", false);
        boolean box10 = sharedPreferences.getBoolean("name10", false);
        boolean box11 = sharedPreferences.getBoolean("name11", false);
        boolean box12 = sharedPreferences.getBoolean("name12", false);
        boolean box13 = sharedPreferences.getBoolean("name13", false);
        boolean box14 = sharedPreferences.getBoolean("name14", false);
        boolean box15 = sharedPreferences.getBoolean("name15", false);
        boolean box16 = sharedPreferences.getBoolean("name16", false);
        boolean box17 = sharedPreferences.getBoolean("name17", false);
        boolean box18 = sharedPreferences.getBoolean("name18", false);
        boolean box19 = sharedPreferences.getBoolean("name19", false);
        boolean box20 = sharedPreferences.getBoolean("name20", false);
        boolean box21 = sharedPreferences.getBoolean("name21", false);
        boolean box22 = sharedPreferences.getBoolean("name22", false);
        boolean box23 = sharedPreferences.getBoolean("name23", false);
        boolean box24 = sharedPreferences.getBoolean("name24", false);
        boolean box25 = sharedPreferences.getBoolean("name25", false);
        boolean box26 = sharedPreferences.getBoolean("name26", false);
        boolean box27 = sharedPreferences.getBoolean("name27", false);
        boolean box28 = sharedPreferences.getBoolean("name28", false);
        boolean box29 = sharedPreferences.getBoolean("name29", false);
        boolean box30 = sharedPreferences.getBoolean("name30", false);
        boolean box31 = sharedPreferences.getBoolean("name31", false);
        boolean box32 = sharedPreferences.getBoolean("name32", false);
        boolean box33 = sharedPreferences.getBoolean("name33", false);
        boolean box34 = sharedPreferences.getBoolean("name34", false);
        boolean box35 = sharedPreferences.getBoolean("name35", false);
        boolean box36 = sharedPreferences.getBoolean("name36", false);
        boolean box37 = sharedPreferences.getBoolean("name37", false);
        boolean box38 = sharedPreferences.getBoolean("name38", false);
        boolean box39 = sharedPreferences.getBoolean("name39", false);
        boolean box40 = sharedPreferences.getBoolean("name40", false);
        boolean box41 = sharedPreferences.getBoolean("name41", false);
        boolean box42 = sharedPreferences.getBoolean("name42", false);
        boolean box43 = sharedPreferences.getBoolean("name43", false);
        boolean box44 = sharedPreferences.getBoolean("name44", false);
        boolean box45 = sharedPreferences.getBoolean("name45", false);
        boolean box46 = sharedPreferences.getBoolean("name46", false);
        boolean box47 = sharedPreferences.getBoolean("name47", false);
        boolean box48 = sharedPreferences.getBoolean("name48", false);
        boolean box49 = sharedPreferences.getBoolean("name49", false);
        boolean box50 = sharedPreferences.getBoolean("name50", false);
        boolean box51 = sharedPreferences.getBoolean("name51", false);
        boolean box52 = sharedPreferences.getBoolean("name52", false);
        boolean box53 = sharedPreferences.getBoolean("name53", false);
        boolean box54 = sharedPreferences.getBoolean("name54", false);
        boolean box55 = sharedPreferences.getBoolean("name55", false);
        boolean box56 = sharedPreferences.getBoolean("name56", false);
        boolean box57 = sharedPreferences.getBoolean("name57", false);
        boolean box58 = sharedPreferences.getBoolean("name58", false);
        boolean box59 = sharedPreferences.getBoolean("name59", false);
        boolean box60 = sharedPreferences.getBoolean("name60", false);
        boolean box61 = sharedPreferences.getBoolean("name61", false);
        boolean box62 = sharedPreferences.getBoolean("name62", false);
        boolean box63 = sharedPreferences.getBoolean("name63", false);
        boolean box64 = sharedPreferences.getBoolean("name64", false);
        boolean box65 = sharedPreferences.getBoolean("name65", false);
        boolean box66 = sharedPreferences.getBoolean("name66", false);
        boolean box67 = sharedPreferences.getBoolean("name67", false);
        boolean box68 = sharedPreferences.getBoolean("name68", false);
        boolean box69 = sharedPreferences.getBoolean("name69", false);
        boolean box70 = sharedPreferences.getBoolean("name70", false);
        boolean box71 = sharedPreferences.getBoolean("name71", false);
        boolean box72 = sharedPreferences.getBoolean("name72", false);
        boolean box73 = sharedPreferences.getBoolean("name73", false);
        boolean box74 = sharedPreferences.getBoolean("name74", false);
        boolean box75 = sharedPreferences.getBoolean("name75", false);
        boolean box76 = sharedPreferences.getBoolean("name76", false);
        boolean box77 = sharedPreferences.getBoolean("name77", false);
        boolean box78 = sharedPreferences.getBoolean("name78", false);
        boolean box79 = sharedPreferences.getBoolean("name79", false);
        boolean box80 = sharedPreferences.getBoolean("name80", false);
        boolean box81 = sharedPreferences.getBoolean("name81", false);
        boolean box82 = sharedPreferences.getBoolean("name82", false);
        boolean box83 = sharedPreferences.getBoolean("name83", false);
        boolean box84 = sharedPreferences.getBoolean("name84", false);
        boolean box85 = sharedPreferences.getBoolean("name85", false);
        boolean box86 = sharedPreferences.getBoolean("name86", false);
        boolean box87 = sharedPreferences.getBoolean("name87", false);
        boolean box88 = sharedPreferences.getBoolean("name88", false);
        boolean box89 = sharedPreferences.getBoolean("name89", false);
        boolean box90 = sharedPreferences.getBoolean("name90", false);
        boolean box91 = sharedPreferences.getBoolean("name91 ", false);
        boolean box92 = sharedPreferences.getBoolean("name92 ", false);
        boolean box93 = sharedPreferences.getBoolean("name93 ", false);
        boolean box94 = sharedPreferences.getBoolean("name94 ", false);
        boolean box95 = sharedPreferences.getBoolean("name95 ", false);
        boolean box96 = sharedPreferences.getBoolean("name96 ", false);
        boolean box97 = sharedPreferences.getBoolean("name97 ", false);
        boolean box98 = sharedPreferences.getBoolean("name98 ", false);
        boolean box99 = sharedPreferences.getBoolean("name99 ", false);
        boolean box100 = sharedPreferences.getBoolean("name100", false);

        boxcheck0 = box0;
        boxcheck1 = box1;
        boxcheck2 = box2;
        boxcheck3 = box3;
        boxcheck4 = box4;
        boxcheck5 = box5;
        boxcheck6 = box6;
        boxcheck7 = box7;
        boxcheck8 = box8;
        boxcheck9 = box9;
        boxcheck10 = box10;
        boxcheck11 = box11;
        boxcheck12 = box12;
        boxcheck13 = box13;
        boxcheck14 = box14;
        boxcheck15 = box15;
        boxcheck16 = box16;
        boxcheck17 = box17;
        boxcheck18 = box18;
        boxcheck19 = box19;
        boxcheck20 = box20;
        boxcheck21 = box21;
        boxcheck22 = box22;
        boxcheck23 = box23;
        boxcheck24 = box24;
        boxcheck25 = box25;
        boxcheck26 = box26;
        boxcheck27 = box27;
        boxcheck28 = box28;
        boxcheck29 = box29;
        boxcheck30 = box30;
        boxcheck31 = box31;
        boxcheck32 = box32;
        boxcheck33 = box33;
        boxcheck34 = box34;
        boxcheck35 = box35;
        boxcheck36 = box36;
        boxcheck37 = box37;
        boxcheck38 = box38;
        boxcheck39 = box39;
        boxcheck40 = box40;
        boxcheck41 = box41;
        boxcheck42 = box42;
        boxcheck43 = box43;
        boxcheck44 = box44;
        boxcheck45 = box45;
        boxcheck46 = box46;
        boxcheck47 = box47;
        boxcheck48 = box48;
        boxcheck49 = box49;
        boxcheck50 = box50;
        boxcheck51 = box51;
        boxcheck52 = box52;
        boxcheck53 = box53;
        boxcheck54 = box54;
        boxcheck55 = box55;
        boxcheck56 = box56;
        boxcheck57 = box57;
        boxcheck58 = box58;
        boxcheck59 = box59;
        boxcheck60 = box60;
        boxcheck61 = box61;
        boxcheck62 = box62;
        boxcheck63 = box63;
        boxcheck64 = box64;
        boxcheck65 = box65;
        boxcheck66 = box66;
        boxcheck67 = box67;
        boxcheck68 = box68;
        boxcheck69 = box69;
        boxcheck70 = box70;
        boxcheck71 = box71;
        boxcheck72 = box72;
        boxcheck73 = box73;
        boxcheck74 = box74;
        boxcheck75 = box75;
        boxcheck76 = box76;
        boxcheck77 = box77;
        boxcheck78 = box78;
        boxcheck79 = box79;
        boxcheck80 = box80;
        boxcheck81 = box81;
        boxcheck82 = box82;
        boxcheck83 = box83;
        boxcheck84 = box84;
        boxcheck85 = box85;
        boxcheck86 = box86;
        boxcheck87 = box87;
        boxcheck88 = box88;
        boxcheck89 = box89;
        boxcheck90 = box90;
        boxcheck91 = box91;
        boxcheck92 = box92;
        boxcheck93 = box93;
        boxcheck94 = box94;
        boxcheck95 = box95;
        boxcheck96 = box96;
        boxcheck97 = box97;
        boxcheck98 = box98;
        boxcheck99 = box99;
        boxcheck100 = box100;


        Log.d(TAG, "load: LOADED");
    }

    //update
    private void update() {
        Log.d(TAG, "update:UPDATED:");
        if (boxcheck0) hiddenquestLayout.setItemChecked(0, true);
        if (boxcheck1) hiddenquestLayout.setItemChecked(1, true);
        if (boxcheck2) hiddenquestLayout.setItemChecked(2, true);
        if (boxcheck3) hiddenquestLayout.setItemChecked(3, true);
        if (boxcheck4) hiddenquestLayout.setItemChecked(4, true);
        if (boxcheck5) hiddenquestLayout.setItemChecked(5, true);
        if (boxcheck6) hiddenquestLayout.setItemChecked(6, true);
        if (boxcheck7) hiddenquestLayout.setItemChecked(7, true);
        if (boxcheck8) hiddenquestLayout.setItemChecked(8, true);
        if (boxcheck9) hiddenquestLayout.setItemChecked(9, true);
        if (boxcheck10) hiddenquestLayout.setItemChecked(10, true);
        if (boxcheck11) hiddenquestLayout.setItemChecked(11, true);
        if (boxcheck12) hiddenquestLayout.setItemChecked(12, true);
        if (boxcheck13) hiddenquestLayout.setItemChecked(13, true);
        if (boxcheck14) hiddenquestLayout.setItemChecked(14, true);
        if (boxcheck15) hiddenquestLayout.setItemChecked(15, true);
        if (boxcheck16) hiddenquestLayout.setItemChecked(16, true);
        if (boxcheck17) hiddenquestLayout.setItemChecked(17, true);
        if (boxcheck18) hiddenquestLayout.setItemChecked(18, true);
        if (boxcheck19) hiddenquestLayout.setItemChecked(19, true);
        if (boxcheck20) hiddenquestLayout.setItemChecked(20, true);
        if (boxcheck21) hiddenquestLayout.setItemChecked(21, true);
        if (boxcheck22) hiddenquestLayout.setItemChecked(22, true);
        if (boxcheck23) hiddenquestLayout.setItemChecked(23, true);
        if (boxcheck24) hiddenquestLayout.setItemChecked(24, true);
        if (boxcheck25) hiddenquestLayout.setItemChecked(25, true);
        if (boxcheck26) hiddenquestLayout.setItemChecked(26, true);
        if (boxcheck27) hiddenquestLayout.setItemChecked(27, true);
        if (boxcheck28) hiddenquestLayout.setItemChecked(28, true);
        if (boxcheck29) hiddenquestLayout.setItemChecked(29, true);
        if (boxcheck30) hiddenquestLayout.setItemChecked(30, true);
        if (boxcheck31) hiddenquestLayout.setItemChecked(31, true);
        if (boxcheck32) hiddenquestLayout.setItemChecked(32, true);
        if (boxcheck33) hiddenquestLayout.setItemChecked(33, true);
        if (boxcheck34) hiddenquestLayout.setItemChecked(34, true);
        if (boxcheck35) hiddenquestLayout.setItemChecked(35, true);
        if (boxcheck36) hiddenquestLayout.setItemChecked(36, true);
        if (boxcheck37) hiddenquestLayout.setItemChecked(37, true);
        if (boxcheck38) hiddenquestLayout.setItemChecked(38, true);
        if (boxcheck39) hiddenquestLayout.setItemChecked(39, true);
        if (boxcheck40) hiddenquestLayout.setItemChecked(40, true);
        if (boxcheck41) hiddenquestLayout.setItemChecked(41, true);
        if (boxcheck42) hiddenquestLayout.setItemChecked(42, true);
        if (boxcheck43) hiddenquestLayout.setItemChecked(43, true);
        if (boxcheck44) hiddenquestLayout.setItemChecked(44, true);
        if (boxcheck45) hiddenquestLayout.setItemChecked(45, true);
        if (boxcheck46) hiddenquestLayout.setItemChecked(46, true);
        if (boxcheck47) hiddenquestLayout.setItemChecked(47, true);
        if (boxcheck48) hiddenquestLayout.setItemChecked(48, true);
        if (boxcheck49) hiddenquestLayout.setItemChecked(49, true);
        if (boxcheck50) hiddenquestLayout.setItemChecked(50, true);
        if (boxcheck51) hiddenquestLayout.setItemChecked(51, true);
        if (boxcheck52) hiddenquestLayout.setItemChecked(52, true);
        if (boxcheck53) hiddenquestLayout.setItemChecked(53, true);
        if (boxcheck54) hiddenquestLayout.setItemChecked(54, true);
        if (boxcheck55) hiddenquestLayout.setItemChecked(55, true);
        if (boxcheck56) hiddenquestLayout.setItemChecked(56, true);
        if (boxcheck57) hiddenquestLayout.setItemChecked(57, true);
        if (boxcheck58) hiddenquestLayout.setItemChecked(58, true);
        if (boxcheck59) hiddenquestLayout.setItemChecked(59, true);
        if (boxcheck60) hiddenquestLayout.setItemChecked(60, true);
        if (boxcheck61) hiddenquestLayout.setItemChecked(61, true);
        if (boxcheck62) hiddenquestLayout.setItemChecked(62, true);
        if (boxcheck63) hiddenquestLayout.setItemChecked(63, true);
        if (boxcheck64) hiddenquestLayout.setItemChecked(64, true);
        if (boxcheck65) hiddenquestLayout.setItemChecked(65, true);
        if (boxcheck66) hiddenquestLayout.setItemChecked(66, true);
        if (boxcheck67) hiddenquestLayout.setItemChecked(67, true);
        if (boxcheck68) hiddenquestLayout.setItemChecked(68, true);
        if (boxcheck69) hiddenquestLayout.setItemChecked(69, true);
        if (boxcheck70) hiddenquestLayout.setItemChecked(70, true);
        if (boxcheck71) hiddenquestLayout.setItemChecked(71, true);
        if (boxcheck72) hiddenquestLayout.setItemChecked(72, true);
        if (boxcheck73) hiddenquestLayout.setItemChecked(73, true);
        if (boxcheck74) hiddenquestLayout.setItemChecked(74, true);
        if (boxcheck75) hiddenquestLayout.setItemChecked(75, true);
        if (boxcheck76) hiddenquestLayout.setItemChecked(76, true);
        if (boxcheck77) hiddenquestLayout.setItemChecked(77, true);
        if (boxcheck78) hiddenquestLayout.setItemChecked(78, true);
        if (boxcheck79) hiddenquestLayout.setItemChecked(79, true);
        if (boxcheck80) hiddenquestLayout.setItemChecked(80, true);
        if (boxcheck81) hiddenquestLayout.setItemChecked(81, true);
        if (boxcheck82) hiddenquestLayout.setItemChecked(82, true);
        if (boxcheck83) hiddenquestLayout.setItemChecked(83, true);
        if (boxcheck84) hiddenquestLayout.setItemChecked(84, true);
        if (boxcheck85) hiddenquestLayout.setItemChecked(85, true);
        if (boxcheck86) hiddenquestLayout.setItemChecked(86, true);
        if (boxcheck87) hiddenquestLayout.setItemChecked(87, true);
        if (boxcheck88) hiddenquestLayout.setItemChecked(88, true);
        if (boxcheck89) hiddenquestLayout.setItemChecked(89, true);
        if (boxcheck90) hiddenquestLayout.setItemChecked(90, true);
        if (boxcheck91) hiddenquestLayout.setItemChecked(91, true);
        if (boxcheck92) hiddenquestLayout.setItemChecked(92, true);
        if (boxcheck93) hiddenquestLayout.setItemChecked(93, true);
        if (boxcheck94) hiddenquestLayout.setItemChecked(94, true);
        if (boxcheck95) hiddenquestLayout.setItemChecked(95, true);
        if (boxcheck96) hiddenquestLayout.setItemChecked(96, true);
        if (boxcheck97) hiddenquestLayout.setItemChecked(97, true);
        if (boxcheck98) hiddenquestLayout.setItemChecked(98, true);
        if (boxcheck99) hiddenquestLayout.setItemChecked(99, true);
        if (boxcheck100) hiddenquestLayout.setItemChecked(100, true);

        return;

    }


}
