package aquino.vladimir.example.xenobladever3;

import android.content.SharedPreferences;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class MercMissionsPage extends AppCompatActivity {
    public static final String TAG = "MercMissionsPage";

    ListView mercmissionsLayout;
    List<String> arrayMercList = new ArrayList<String>();
    MercMissionsList mercMissionsList = new MercMissionsList();
    ArrayAdapter adMM;

    private boolean boxcheck0;
    private boolean boxcheck1;
    private boolean boxcheck2;
    private boolean boxcheck3;
    private boolean boxcheck4;
    private boolean boxcheck5;
    private boolean boxcheck6;
    private boolean boxcheck7;
    private boolean boxcheck8;
    private boolean boxcheck9;
    private boolean boxcheck10;
    private boolean boxcheck11;
    private boolean boxcheck12;
    private boolean boxcheck13;
    private boolean boxcheck14;
    private boolean boxcheck15;
    private boolean boxcheck16;
    private boolean boxcheck17;
    private boolean boxcheck18;
    private boolean boxcheck19;
    private boolean boxcheck20;
    private boolean boxcheck21;
    private boolean boxcheck22;
    private boolean boxcheck23;
    private boolean boxcheck24;
    private boolean boxcheck25;
    private boolean boxcheck26;
    private boolean boxcheck27;
    private boolean boxcheck28;
    private boolean boxcheck29;
    private boolean boxcheck30;
    private boolean boxcheck31;
    private boolean boxcheck32;
    private boolean boxcheck33;
    private boolean boxcheck34;
    private boolean boxcheck35;
    private boolean boxcheck36;
    private boolean boxcheck37;
    private boolean boxcheck38;
    private boolean boxcheck39;
    private boolean boxcheck40;
    private boolean boxcheck41;
    private boolean boxcheck42;
    private boolean boxcheck43;
    private boolean boxcheck44;
    private boolean boxcheck45;
    private boolean boxcheck46;
    private boolean boxcheck47;
    private boolean boxcheck48;
    private boolean boxcheck49;
    private boolean boxcheck50;
    private boolean boxcheck51;
    private boolean boxcheck52;
    private boolean boxcheck53;
    private boolean boxcheck54;
    private boolean boxcheck55;
    private boolean boxcheck56;
    private boolean boxcheck57;
    private boolean boxcheck58;
    private boolean boxcheck59;
    private boolean boxcheck60;
    private boolean boxcheck61;
    private boolean boxcheck62;
    private boolean boxcheck63;
    private boolean boxcheck64;
    private boolean boxcheck65;
    private boolean boxcheck66;
    private boolean boxcheck67;
    private boolean boxcheck68;
    private boolean boxcheck69;
    private boolean boxcheck70;
    private boolean boxcheck71;
    private boolean boxcheck72;
    private boolean boxcheck73;
    private boolean boxcheck74;
    private boolean boxcheck75;
    private boolean boxcheck76;
    private boolean boxcheck77;
    private boolean boxcheck78;
    private boolean boxcheck79;
    private boolean boxcheck80;
    private boolean boxcheck81;
    private boolean boxcheck82;
    private boolean boxcheck83;
    private boolean boxcheck84;
    private boolean boxcheck85;
    private boolean boxcheck86;
    private boolean boxcheck87;
    private boolean boxcheck88;
    private boolean boxcheck89;
    private boolean boxcheck90;
    private boolean boxcheck91;
    private boolean boxcheck92;
    private boolean boxcheck93;
    private boolean boxcheck94;
    private boolean boxcheck95;
    private boolean boxcheck96;
    private boolean boxcheck97;
    private boolean boxcheck98;
    private boolean boxcheck99;
    private boolean boxcheck100;
    private boolean boxcheck101;
    private boolean boxcheck102;
    private boolean boxcheck103;
    private boolean boxcheck104;
    private boolean boxcheck105;
    private boolean boxcheck106;
    private boolean boxcheck107;
    private boolean boxcheck108;
    private boolean boxcheck109;
    private boolean boxcheck110;
    private boolean boxcheck111;
    private boolean boxcheck112;
    private boolean boxcheck113;
    private boolean boxcheck114;
    private boolean boxcheck115;
    private boolean boxcheck116;
    private boolean boxcheck117;
    private boolean boxcheck118;
    private boolean boxcheck119;
    private boolean boxcheck120;
    private boolean boxcheck121;
    private boolean boxcheck122;
    private boolean boxcheck123;
    private boolean boxcheck124;
    private boolean boxcheck125;
    private boolean boxcheck126;
    private boolean boxcheck127;
    private boolean boxcheck128;
    private boolean boxcheck129;
    private boolean boxcheck130;
    private boolean boxcheck131;
    private boolean boxcheck132;
    private boolean boxcheck133;
    private boolean boxcheck134;
    private boolean boxcheck135;
    private boolean boxcheck136;
    private boolean boxcheck137;
    private boolean boxcheck138;
    private boolean boxcheck139;
    private boolean boxcheck140;
    private boolean boxcheck141;
    private boolean boxcheck142;
    private boolean boxcheck143;
    private boolean boxcheck144;
    private boolean boxcheck145;
    private boolean boxcheck146;
    private boolean boxcheck147;
    private boolean boxcheck148;
    private boolean boxcheck149;
    private boolean boxcheck150;
    private boolean boxcheck151;
    private boolean boxcheck152;
    private boolean boxcheck153;
    private boolean boxcheck154;
    private boolean boxcheck155;
    private boolean boxcheck156;
    private boolean boxcheck157;
    private boolean boxcheck158;
    private boolean boxcheck159;
    private boolean boxcheck160;
    private boolean boxcheck161;
    private boolean boxcheck162;
    private boolean boxcheck163;
    private boolean boxcheck164;
    private boolean boxcheck165;
    private boolean boxcheck166;
    private boolean boxcheck167;
    private boolean boxcheck168;
    private boolean boxcheck169;
    private boolean boxcheck170;
    private boolean boxcheck171;
    private boolean boxcheck172;
    private boolean boxcheck173;
    private boolean boxcheck174;
    private boolean boxcheck175;
    private boolean boxcheck176;
    private boolean boxcheck177;
    private boolean boxcheck178;
    private boolean boxcheck179;
    private boolean boxcheck180;
    private boolean boxcheck181;
    private boolean boxcheck182;
    private boolean boxcheck183;
    private boolean boxcheck184;
    private boolean boxcheck185;
    private boolean boxcheck186;
    private boolean boxcheck187;
    private boolean boxcheck188;
    private boolean boxcheck189;
    private boolean boxcheck190;
    private boolean boxcheck191;
    private boolean boxcheck192;
    private boolean boxcheck193;
    private boolean boxcheck194;
    private boolean boxcheck195;
    private boolean boxcheck196;
    private boolean boxcheck197;
    private boolean boxcheck198;
    private boolean boxcheck199;
    private boolean boxcheck200;
    private boolean boxcheck201;
    private boolean boxcheck202;
    private boolean boxcheck203;
    private boolean boxcheck204;
    private boolean boxcheck205;
    private boolean boxcheck206;
    private boolean boxcheck207;
    private boolean boxcheck208;
    private boolean boxcheck209;
    private boolean boxcheck210;
    private boolean boxcheck211;
    private boolean boxcheck212;
    private boolean boxcheck213;
    private boolean boxcheck214;
    private boolean boxcheck215;
    private boolean boxcheck216;
    private boolean boxcheck217;
    private boolean boxcheck218;
    private boolean boxcheck219;
    private boolean boxcheck220;
    private boolean boxcheck221;
    private boolean boxcheck222;
    private boolean boxcheck223;
    private boolean boxcheck224;
    private boolean boxcheck225;
    private boolean boxcheck226;
    private boolean boxcheck227;
    private boolean boxcheck228;
    private boolean boxcheck229;
    private boolean boxcheck230;
    private boolean boxcheck231;
    private boolean boxcheck232;
    private boolean boxcheck233;
    private boolean boxcheck234;
    private boolean boxcheck235;
    private boolean boxcheck236;
    private boolean boxcheck237;
    private boolean boxcheck238;
    private boolean boxcheck239;
    private boolean boxcheck240;
    private boolean boxcheck241;
    private boolean boxcheck242;
    private boolean boxcheck243;
    private boolean boxcheck244;
    private boolean boxcheck245;
    private boolean boxcheck246;
    private boolean boxcheck247;
    private boolean boxcheck248;
    private boolean boxcheck249;
    private boolean boxcheck250;
    private boolean boxcheck251;
    private boolean boxcheck252;
    private boolean boxcheck253;
    private boolean boxcheck254;
    private boolean boxcheck255;
    private boolean boxcheck256;
    private boolean boxcheck257;
    private boolean boxcheck258;
    private boolean boxcheck259;
    private boolean boxcheck260;
    private boolean boxcheck261;
    private boolean boxcheck262;
    private boolean boxcheck263;
    private boolean boxcheck264;
    private boolean boxcheck265;
    private boolean boxcheck266;
    private boolean boxcheck267;
    private boolean boxcheck268;
    private boolean boxcheck269;
    private boolean boxcheck270;
    private boolean boxcheck271;
    private boolean boxcheck272;
    private boolean boxcheck273;
    private boolean boxcheck274;
    private boolean boxcheck275;
    private boolean boxcheck276;
    private boolean boxcheck277;
    private boolean boxcheck278;
    private boolean boxcheck279;
    private boolean boxcheck280;
    private boolean boxcheck281;
    private boolean boxcheck282;
    private boolean boxcheck283;
    private boolean boxcheck284;
    private boolean boxcheck285;
    private boolean boxcheck286;
    private boolean boxcheck287;
    private boolean boxcheck288;
    private boolean boxcheck289;
    private boolean boxcheck290;
    private boolean boxcheck291;
    private boolean boxcheck292;
    private boolean boxcheck293;
    private boolean boxcheck294;
    private boolean boxcheck295;
    private boolean boxcheck296;
    private boolean boxcheck297;
    private boolean boxcheck298;
    private boolean boxcheck299;
    private boolean boxcheck300;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_merc_missions_page);
        mercmissionsLayout = findViewById(R.id.mercmissionsLayout);


        //adapter set
        arrayMercList = new ArrayList<String>(Arrays.asList(mercMissionsList.MercMissionsListBig));


        adMM = new ArrayAdapter(this, android.R.layout.select_dialog_multichoice, arrayMercList);
        mercmissionsLayout.setAdapter(adMM);
        Collections.sort(arrayMercList);

        adMM.notifyDataSetChanged();

        mercmissionsLayout.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                int ammount;
                ammount = arrayMercList.size();
                Toast.makeText(MercMissionsPage.this, "position" + position + "size" + ammount, Toast.LENGTH_SHORT).show();
                boxcheck1 = mercmissionsLayout.isItemChecked(1);
                boxcheck2 = mercmissionsLayout.isItemChecked(2);
                boxcheck3 = mercmissionsLayout.isItemChecked(3);
                boxcheck4 = mercmissionsLayout.isItemChecked(4);
                boxcheck5 = mercmissionsLayout.isItemChecked(5);
                boxcheck6 = mercmissionsLayout.isItemChecked(6);
                boxcheck7 = mercmissionsLayout.isItemChecked(7);
                boxcheck8 = mercmissionsLayout.isItemChecked(8);
                boxcheck9 = mercmissionsLayout.isItemChecked(9);
                boxcheck10 = mercmissionsLayout.isItemChecked(10);
                boxcheck11 = mercmissionsLayout.isItemChecked(11);
                boxcheck12 = mercmissionsLayout.isItemChecked(12);
                boxcheck13 = mercmissionsLayout.isItemChecked(13);
                boxcheck14 = mercmissionsLayout.isItemChecked(14);
                boxcheck15 = mercmissionsLayout.isItemChecked(15);
                boxcheck16 = mercmissionsLayout.isItemChecked(16);
                boxcheck17 = mercmissionsLayout.isItemChecked(17);
                boxcheck18 = mercmissionsLayout.isItemChecked(18);
                boxcheck19 = mercmissionsLayout.isItemChecked(19);
                boxcheck20 = mercmissionsLayout.isItemChecked(20);
                boxcheck21 = mercmissionsLayout.isItemChecked(21);
                boxcheck22 = mercmissionsLayout.isItemChecked(22);
                boxcheck23 = mercmissionsLayout.isItemChecked(23);
                boxcheck24 = mercmissionsLayout.isItemChecked(24);
                boxcheck25 = mercmissionsLayout.isItemChecked(25);
                boxcheck26 = mercmissionsLayout.isItemChecked(26);
                boxcheck27 = mercmissionsLayout.isItemChecked(27);
                boxcheck28 = mercmissionsLayout.isItemChecked(28);
                boxcheck29 = mercmissionsLayout.isItemChecked(29);
                boxcheck30 = mercmissionsLayout.isItemChecked(30);
                boxcheck31 = mercmissionsLayout.isItemChecked(31);
                boxcheck32 = mercmissionsLayout.isItemChecked(32);
                boxcheck33 = mercmissionsLayout.isItemChecked(33);
                boxcheck34 = mercmissionsLayout.isItemChecked(34);
                boxcheck35 = mercmissionsLayout.isItemChecked(35);
                boxcheck36 = mercmissionsLayout.isItemChecked(36);
                boxcheck37 = mercmissionsLayout.isItemChecked(37);
                boxcheck38 = mercmissionsLayout.isItemChecked(38);
                boxcheck39 = mercmissionsLayout.isItemChecked(39);
                boxcheck40 = mercmissionsLayout.isItemChecked(40);
                boxcheck41 = mercmissionsLayout.isItemChecked(41);
                boxcheck42 = mercmissionsLayout.isItemChecked(42);
                boxcheck43 = mercmissionsLayout.isItemChecked(43);
                boxcheck44 = mercmissionsLayout.isItemChecked(44);
                boxcheck45 = mercmissionsLayout.isItemChecked(45);
                boxcheck46 = mercmissionsLayout.isItemChecked(46);
                boxcheck47 = mercmissionsLayout.isItemChecked(47);
                boxcheck48 = mercmissionsLayout.isItemChecked(48);
                boxcheck49 = mercmissionsLayout.isItemChecked(49);
                boxcheck50 = mercmissionsLayout.isItemChecked(50);
                boxcheck51 = mercmissionsLayout.isItemChecked(51);
                boxcheck52 = mercmissionsLayout.isItemChecked(52);
                boxcheck53 = mercmissionsLayout.isItemChecked(53);
                boxcheck54 = mercmissionsLayout.isItemChecked(54);
                boxcheck55 = mercmissionsLayout.isItemChecked(55);
                boxcheck56 = mercmissionsLayout.isItemChecked(56);
                boxcheck57 = mercmissionsLayout.isItemChecked(57);
                boxcheck58 = mercmissionsLayout.isItemChecked(58);
                boxcheck59 = mercmissionsLayout.isItemChecked(59);
                boxcheck60 = mercmissionsLayout.isItemChecked(60);
                boxcheck61 = mercmissionsLayout.isItemChecked(61);
                boxcheck62 = mercmissionsLayout.isItemChecked(62);
                boxcheck63 = mercmissionsLayout.isItemChecked(63);
                boxcheck64 = mercmissionsLayout.isItemChecked(64);
                boxcheck65 = mercmissionsLayout.isItemChecked(65);
                boxcheck66 = mercmissionsLayout.isItemChecked(66);
                boxcheck67 = mercmissionsLayout.isItemChecked(67);
                boxcheck68 = mercmissionsLayout.isItemChecked(68);
                boxcheck69 = mercmissionsLayout.isItemChecked(69);
                boxcheck70 = mercmissionsLayout.isItemChecked(70);
                boxcheck71 = mercmissionsLayout.isItemChecked(71);
                boxcheck72 = mercmissionsLayout.isItemChecked(72);
                boxcheck73 = mercmissionsLayout.isItemChecked(73);
                boxcheck74 = mercmissionsLayout.isItemChecked(74);
                boxcheck75 = mercmissionsLayout.isItemChecked(75);
                boxcheck76 = mercmissionsLayout.isItemChecked(76);
                boxcheck77 = mercmissionsLayout.isItemChecked(77);
                boxcheck78 = mercmissionsLayout.isItemChecked(78);
                boxcheck79 = mercmissionsLayout.isItemChecked(79);
                boxcheck80 = mercmissionsLayout.isItemChecked(80);
                boxcheck81 = mercmissionsLayout.isItemChecked(81);
                boxcheck82 = mercmissionsLayout.isItemChecked(82);
                boxcheck83 = mercmissionsLayout.isItemChecked(83);
                boxcheck84 = mercmissionsLayout.isItemChecked(84);
                boxcheck85 = mercmissionsLayout.isItemChecked(85);
                boxcheck86 = mercmissionsLayout.isItemChecked(86);
                boxcheck87 = mercmissionsLayout.isItemChecked(87);
                boxcheck88 = mercmissionsLayout.isItemChecked(88);
                boxcheck89 = mercmissionsLayout.isItemChecked(89);
                boxcheck90 = mercmissionsLayout.isItemChecked(90);
                boxcheck91 = mercmissionsLayout.isItemChecked(91);
                boxcheck92 = mercmissionsLayout.isItemChecked(92);
                boxcheck93 = mercmissionsLayout.isItemChecked(93);
                boxcheck94 = mercmissionsLayout.isItemChecked(94);
                boxcheck95 = mercmissionsLayout.isItemChecked(95);
                boxcheck96 = mercmissionsLayout.isItemChecked(96);
                boxcheck97 = mercmissionsLayout.isItemChecked(97);
                boxcheck98 = mercmissionsLayout.isItemChecked(98);
                boxcheck99 = mercmissionsLayout.isItemChecked(99);
                boxcheck100 = mercmissionsLayout.isItemChecked(100);
                boxcheck101 = mercmissionsLayout.isItemChecked(101);
                boxcheck102 = mercmissionsLayout.isItemChecked(102);
                boxcheck103 = mercmissionsLayout.isItemChecked(103);
                boxcheck104 = mercmissionsLayout.isItemChecked(104);
                boxcheck105 = mercmissionsLayout.isItemChecked(105);
                boxcheck106 = mercmissionsLayout.isItemChecked(106);
                boxcheck107 = mercmissionsLayout.isItemChecked(107);
                boxcheck108 = mercmissionsLayout.isItemChecked(108);
                boxcheck109 = mercmissionsLayout.isItemChecked(109);
                boxcheck110 = mercmissionsLayout.isItemChecked(110);
                boxcheck111 = mercmissionsLayout.isItemChecked(111);
                boxcheck112 = mercmissionsLayout.isItemChecked(112);
                boxcheck113 = mercmissionsLayout.isItemChecked(113);
                boxcheck114 = mercmissionsLayout.isItemChecked(114);
                boxcheck115 = mercmissionsLayout.isItemChecked(115);
                boxcheck116 = mercmissionsLayout.isItemChecked(116);
                boxcheck117 = mercmissionsLayout.isItemChecked(117);
                boxcheck118 = mercmissionsLayout.isItemChecked(118);
                boxcheck119 = mercmissionsLayout.isItemChecked(119);
                boxcheck120 = mercmissionsLayout.isItemChecked(120);
                boxcheck121 = mercmissionsLayout.isItemChecked(121);
                boxcheck122 = mercmissionsLayout.isItemChecked(122);
                boxcheck123 = mercmissionsLayout.isItemChecked(123);
                boxcheck124 = mercmissionsLayout.isItemChecked(124);
                boxcheck125 = mercmissionsLayout.isItemChecked(125);
                boxcheck126 = mercmissionsLayout.isItemChecked(126);
                boxcheck127 = mercmissionsLayout.isItemChecked(127);
                boxcheck128 = mercmissionsLayout.isItemChecked(128);
                boxcheck129 = mercmissionsLayout.isItemChecked(129);
                boxcheck130 = mercmissionsLayout.isItemChecked(130);
                boxcheck131 = mercmissionsLayout.isItemChecked(131);
                boxcheck132 = mercmissionsLayout.isItemChecked(132);
                boxcheck133 = mercmissionsLayout.isItemChecked(133);
                boxcheck134 = mercmissionsLayout.isItemChecked(134);
                boxcheck135 = mercmissionsLayout.isItemChecked(135);
                boxcheck136 = mercmissionsLayout.isItemChecked(136);
                boxcheck137 = mercmissionsLayout.isItemChecked(137);
                boxcheck138 = mercmissionsLayout.isItemChecked(138);
                boxcheck139 = mercmissionsLayout.isItemChecked(139);
                boxcheck140 = mercmissionsLayout.isItemChecked(140);
                boxcheck141 = mercmissionsLayout.isItemChecked(141);
                boxcheck142 = mercmissionsLayout.isItemChecked(142);
                boxcheck143 = mercmissionsLayout.isItemChecked(143);
                boxcheck144 = mercmissionsLayout.isItemChecked(144);
                boxcheck145 = mercmissionsLayout.isItemChecked(145);
                boxcheck146 = mercmissionsLayout.isItemChecked(146);
                boxcheck147 = mercmissionsLayout.isItemChecked(147);
                boxcheck148 = mercmissionsLayout.isItemChecked(148);
                boxcheck149 = mercmissionsLayout.isItemChecked(149);
                boxcheck150 = mercmissionsLayout.isItemChecked(150);
                boxcheck151 = mercmissionsLayout.isItemChecked(151);
                boxcheck152 = mercmissionsLayout.isItemChecked(152);
                boxcheck153 = mercmissionsLayout.isItemChecked(153);
                boxcheck154 = mercmissionsLayout.isItemChecked(154);
                boxcheck155 = mercmissionsLayout.isItemChecked(155);
                boxcheck156 = mercmissionsLayout.isItemChecked(156);
                boxcheck157 = mercmissionsLayout.isItemChecked(157);
                boxcheck158 = mercmissionsLayout.isItemChecked(158);
                boxcheck159 = mercmissionsLayout.isItemChecked(159);
                boxcheck160 = mercmissionsLayout.isItemChecked(160);
                boxcheck161 = mercmissionsLayout.isItemChecked(161);
                boxcheck162 = mercmissionsLayout.isItemChecked(162);
                boxcheck163 = mercmissionsLayout.isItemChecked(163);
                boxcheck164 = mercmissionsLayout.isItemChecked(164);
                boxcheck165 = mercmissionsLayout.isItemChecked(165);
                boxcheck166 = mercmissionsLayout.isItemChecked(166);
                boxcheck167 = mercmissionsLayout.isItemChecked(167);
                boxcheck168 = mercmissionsLayout.isItemChecked(168);
                boxcheck169 = mercmissionsLayout.isItemChecked(169);
                boxcheck170 = mercmissionsLayout.isItemChecked(170);
                boxcheck171 = mercmissionsLayout.isItemChecked(171);
                boxcheck172 = mercmissionsLayout.isItemChecked(172);
                boxcheck173 = mercmissionsLayout.isItemChecked(173);
                boxcheck174 = mercmissionsLayout.isItemChecked(174);
                boxcheck175 = mercmissionsLayout.isItemChecked(175);
                boxcheck176 = mercmissionsLayout.isItemChecked(176);
                boxcheck177 = mercmissionsLayout.isItemChecked(177);
                boxcheck178 = mercmissionsLayout.isItemChecked(178);
                boxcheck179 = mercmissionsLayout.isItemChecked(179);
                boxcheck180 = mercmissionsLayout.isItemChecked(180);
                boxcheck181 = mercmissionsLayout.isItemChecked(181);
                boxcheck182 = mercmissionsLayout.isItemChecked(182);
                boxcheck183 = mercmissionsLayout.isItemChecked(183);
                boxcheck184 = mercmissionsLayout.isItemChecked(184);
                boxcheck185 = mercmissionsLayout.isItemChecked(185);
                boxcheck186 = mercmissionsLayout.isItemChecked(186);
                boxcheck187 = mercmissionsLayout.isItemChecked(187);
                boxcheck188 = mercmissionsLayout.isItemChecked(188);
                boxcheck189 = mercmissionsLayout.isItemChecked(189);
                boxcheck190 = mercmissionsLayout.isItemChecked(190);
                boxcheck191 = mercmissionsLayout.isItemChecked(191);
                boxcheck192 = mercmissionsLayout.isItemChecked(192);
                boxcheck193 = mercmissionsLayout.isItemChecked(193);
                boxcheck194 = mercmissionsLayout.isItemChecked(194);
                boxcheck195 = mercmissionsLayout.isItemChecked(195);
                boxcheck196 = mercmissionsLayout.isItemChecked(196);
                boxcheck197 = mercmissionsLayout.isItemChecked(197);
                boxcheck198 = mercmissionsLayout.isItemChecked(198);
                boxcheck199 = mercmissionsLayout.isItemChecked(199);
                boxcheck200 = mercmissionsLayout.isItemChecked(200);
                boxcheck201 = mercmissionsLayout.isItemChecked(201);
                boxcheck202 = mercmissionsLayout.isItemChecked(202);
                boxcheck203 = mercmissionsLayout.isItemChecked(203);
                boxcheck204 = mercmissionsLayout.isItemChecked(204);
                boxcheck205 = mercmissionsLayout.isItemChecked(205);
                boxcheck206 = mercmissionsLayout.isItemChecked(206);
                boxcheck207 = mercmissionsLayout.isItemChecked(207);
                boxcheck208 = mercmissionsLayout.isItemChecked(208);
                boxcheck209 = mercmissionsLayout.isItemChecked(209);
                boxcheck210 = mercmissionsLayout.isItemChecked(210);
                boxcheck211 = mercmissionsLayout.isItemChecked(211);
                boxcheck212 = mercmissionsLayout.isItemChecked(212);
                boxcheck213 = mercmissionsLayout.isItemChecked(213);
                boxcheck214 = mercmissionsLayout.isItemChecked(214);
                boxcheck215 = mercmissionsLayout.isItemChecked(215);
                boxcheck216 = mercmissionsLayout.isItemChecked(216);
                boxcheck217 = mercmissionsLayout.isItemChecked(217);
                boxcheck218 = mercmissionsLayout.isItemChecked(218);
                boxcheck219 = mercmissionsLayout.isItemChecked(219);
                boxcheck220 = mercmissionsLayout.isItemChecked(220);
                boxcheck221 = mercmissionsLayout.isItemChecked(221);
                boxcheck222 = mercmissionsLayout.isItemChecked(222);
                boxcheck223 = mercmissionsLayout.isItemChecked(223);
                boxcheck224 = mercmissionsLayout.isItemChecked(224);
                boxcheck225 = mercmissionsLayout.isItemChecked(225);
                boxcheck226 = mercmissionsLayout.isItemChecked(226);
                boxcheck227 = mercmissionsLayout.isItemChecked(227);
                boxcheck228 = mercmissionsLayout.isItemChecked(228);
                boxcheck229 = mercmissionsLayout.isItemChecked(229);
                boxcheck230 = mercmissionsLayout.isItemChecked(230);
                boxcheck231 = mercmissionsLayout.isItemChecked(231);
                boxcheck232 = mercmissionsLayout.isItemChecked(232);
                boxcheck233 = mercmissionsLayout.isItemChecked(233);
                boxcheck234 = mercmissionsLayout.isItemChecked(234);
                boxcheck235 = mercmissionsLayout.isItemChecked(235);
                boxcheck236 = mercmissionsLayout.isItemChecked(236);
                boxcheck237 = mercmissionsLayout.isItemChecked(237);
                boxcheck238 = mercmissionsLayout.isItemChecked(238);
                boxcheck239 = mercmissionsLayout.isItemChecked(239);
                boxcheck240 = mercmissionsLayout.isItemChecked(240);
                boxcheck241 = mercmissionsLayout.isItemChecked(241);
                boxcheck242 = mercmissionsLayout.isItemChecked(242);
                boxcheck243 = mercmissionsLayout.isItemChecked(243);
                boxcheck244 = mercmissionsLayout.isItemChecked(244);
                boxcheck245 = mercmissionsLayout.isItemChecked(245);
                boxcheck246 = mercmissionsLayout.isItemChecked(246);
                boxcheck247 = mercmissionsLayout.isItemChecked(247);
                boxcheck248 = mercmissionsLayout.isItemChecked(248);
                boxcheck249 = mercmissionsLayout.isItemChecked(249);
                boxcheck250 = mercmissionsLayout.isItemChecked(250);
                boxcheck251 = mercmissionsLayout.isItemChecked(251);
                boxcheck252 = mercmissionsLayout.isItemChecked(252);
                boxcheck253 = mercmissionsLayout.isItemChecked(253);
                boxcheck254 = mercmissionsLayout.isItemChecked(254);
                boxcheck255 = mercmissionsLayout.isItemChecked(255);
                boxcheck256 = mercmissionsLayout.isItemChecked(256);
                boxcheck257 = mercmissionsLayout.isItemChecked(257);
                boxcheck258 = mercmissionsLayout.isItemChecked(258);
                boxcheck259 = mercmissionsLayout.isItemChecked(259);
                boxcheck260 = mercmissionsLayout.isItemChecked(260);
                boxcheck261 = mercmissionsLayout.isItemChecked(261);
                boxcheck262 = mercmissionsLayout.isItemChecked(262);
                boxcheck263 = mercmissionsLayout.isItemChecked(263);
                boxcheck264 = mercmissionsLayout.isItemChecked(264);
                boxcheck265 = mercmissionsLayout.isItemChecked(265);
                boxcheck266 = mercmissionsLayout.isItemChecked(266);
                boxcheck267 = mercmissionsLayout.isItemChecked(267);
                boxcheck268 = mercmissionsLayout.isItemChecked(268);
                boxcheck269 = mercmissionsLayout.isItemChecked(269);
                boxcheck270 = mercmissionsLayout.isItemChecked(270);
                boxcheck271 = mercmissionsLayout.isItemChecked(271);
                boxcheck272 = mercmissionsLayout.isItemChecked(272);
                boxcheck273 = mercmissionsLayout.isItemChecked(273);
                boxcheck274 = mercmissionsLayout.isItemChecked(274);
                boxcheck275 = mercmissionsLayout.isItemChecked(275);
                boxcheck276 = mercmissionsLayout.isItemChecked(276);
                boxcheck277 = mercmissionsLayout.isItemChecked(277);
                boxcheck278 = mercmissionsLayout.isItemChecked(278);
                boxcheck279 = mercmissionsLayout.isItemChecked(279);
                boxcheck280 = mercmissionsLayout.isItemChecked(280);
                boxcheck281 = mercmissionsLayout.isItemChecked(281);
                boxcheck282 = mercmissionsLayout.isItemChecked(282);
                boxcheck283 = mercmissionsLayout.isItemChecked(283);
                boxcheck284 = mercmissionsLayout.isItemChecked(284);
                boxcheck285 = mercmissionsLayout.isItemChecked(285);
                boxcheck286 = mercmissionsLayout.isItemChecked(286);
                boxcheck287 = mercmissionsLayout.isItemChecked(287);
                boxcheck288 = mercmissionsLayout.isItemChecked(288);
                boxcheck289 = mercmissionsLayout.isItemChecked(289);
                boxcheck290 = mercmissionsLayout.isItemChecked(290);
                boxcheck291 = mercmissionsLayout.isItemChecked(291);
                boxcheck292 = mercmissionsLayout.isItemChecked(292);
                boxcheck293 = mercmissionsLayout.isItemChecked(293);
                boxcheck294 = mercmissionsLayout.isItemChecked(294);
                boxcheck295 = mercmissionsLayout.isItemChecked(295);
                boxcheck296 = mercmissionsLayout.isItemChecked(296);
                boxcheck297 = mercmissionsLayout.isItemChecked(297);
                boxcheck298 = mercmissionsLayout.isItemChecked(298);
                boxcheck299 = mercmissionsLayout.isItemChecked(299);
                boxcheck300 = mercmissionsLayout.isItemChecked(300);


                save();

            }
        });

        load();
        update();
    }


    //save
    private void save() {

        SharedPreferences sharedPreferences = getSharedPreferences("MyData", MODE_PRIVATE);
        SharedPreferences.Editor editor = sharedPreferences.edit();

        editor.putBoolean("name0", boxcheck0);
        editor.putBoolean("name1", boxcheck1);
        editor.putBoolean("name2", boxcheck2);
        editor.putBoolean("name3", boxcheck3);
        editor.putBoolean("name4", boxcheck4);
        editor.putBoolean("name5", boxcheck5);
        editor.putBoolean("name6", boxcheck6);
        editor.putBoolean("name7", boxcheck7);
        editor.putBoolean("name8", boxcheck8);
        editor.putBoolean("name9", boxcheck9);
        editor.putBoolean("name10", boxcheck10);
        editor.putBoolean("name11", boxcheck11);
        editor.putBoolean("name12", boxcheck12);
        editor.putBoolean("name13", boxcheck13);
        editor.putBoolean("name14", boxcheck14);
        editor.putBoolean("name15", boxcheck15);
        editor.putBoolean("name16", boxcheck16);
        editor.putBoolean("name17", boxcheck17);
        editor.putBoolean("name18", boxcheck18);
        editor.putBoolean("name19", boxcheck19);
        editor.putBoolean("name20", boxcheck20);
        editor.putBoolean("name21", boxcheck21);
        editor.putBoolean("name22", boxcheck22);
        editor.putBoolean("name23", boxcheck23);
        editor.putBoolean("name24", boxcheck24);
        editor.putBoolean("name25", boxcheck25);
        editor.putBoolean("name26", boxcheck26);
        editor.putBoolean("name27", boxcheck27);
        editor.putBoolean("name28", boxcheck28);
        editor.putBoolean("name29", boxcheck29);
        editor.putBoolean("name30", boxcheck30);
        editor.putBoolean("name31", boxcheck31);
        editor.putBoolean("name32", boxcheck32);
        editor.putBoolean("name33", boxcheck33);
        editor.putBoolean("name34", boxcheck34);
        editor.putBoolean("name35", boxcheck35);
        editor.putBoolean("name36", boxcheck36);
        editor.putBoolean("name37", boxcheck37);
        editor.putBoolean("name38", boxcheck38);
        editor.putBoolean("name39", boxcheck39);
        editor.putBoolean("name40", boxcheck40);
        editor.putBoolean("name41", boxcheck41);
        editor.putBoolean("name42", boxcheck42);
        editor.putBoolean("name43", boxcheck43);
        editor.putBoolean("name44", boxcheck44);
        editor.putBoolean("name45", boxcheck45);
        editor.putBoolean("name46", boxcheck46);
        editor.putBoolean("name47", boxcheck47);
        editor.putBoolean("name48", boxcheck48);
        editor.putBoolean("name49", boxcheck49);
        editor.putBoolean("name50", boxcheck50);
        editor.putBoolean("name51", boxcheck51);
        editor.putBoolean("name52", boxcheck52);
        editor.putBoolean("name53", boxcheck53);
        editor.putBoolean("name54", boxcheck54);
        editor.putBoolean("name55", boxcheck55);
        editor.putBoolean("name56", boxcheck56);
        editor.putBoolean("name57", boxcheck57);
        editor.putBoolean("name58", boxcheck58);
        editor.putBoolean("name59", boxcheck59);
        editor.putBoolean("name60", boxcheck60);
        editor.putBoolean("name61", boxcheck61);
        editor.putBoolean("name62", boxcheck62);
        editor.putBoolean("name63", boxcheck63);
        editor.putBoolean("name64", boxcheck64);
        editor.putBoolean("name65", boxcheck65);
        editor.putBoolean("name66", boxcheck66);
        editor.putBoolean("name67", boxcheck67);
        editor.putBoolean("name68", boxcheck68);
        editor.putBoolean("name69", boxcheck69);
        editor.putBoolean("name70", boxcheck70);
        editor.putBoolean("name71", boxcheck71);
        editor.putBoolean("name72", boxcheck72);
        editor.putBoolean("name73", boxcheck73);
        editor.putBoolean("name74", boxcheck74);
        editor.putBoolean("name75", boxcheck75);
        editor.putBoolean("name76", boxcheck76);
        editor.putBoolean("name77", boxcheck77);
        editor.putBoolean("name78", boxcheck78);
        editor.putBoolean("name79", boxcheck79);
        editor.putBoolean("name80", boxcheck80);
        editor.putBoolean("name81", boxcheck81);
        editor.putBoolean("name82", boxcheck82);
        editor.putBoolean("name83", boxcheck83);
        editor.putBoolean("name84", boxcheck84);
        editor.putBoolean("name85", boxcheck85);
        editor.putBoolean("name86", boxcheck86);
        editor.putBoolean("name87", boxcheck87);
        editor.putBoolean("name88", boxcheck88);
        editor.putBoolean("name89", boxcheck89);
        editor.putBoolean("name90", boxcheck90);
        editor.putBoolean("name91", boxcheck91);
        editor.putBoolean("name92", boxcheck92);
        editor.putBoolean("name93", boxcheck93);
        editor.putBoolean("name94", boxcheck94);
        editor.putBoolean("name95", boxcheck95);
        editor.putBoolean("name96", boxcheck96);
        editor.putBoolean("name97", boxcheck97);
        editor.putBoolean("name98", boxcheck98);
        editor.putBoolean("name99", boxcheck99);
        editor.putBoolean("name100", boxcheck100);
        editor.putBoolean("name101", boxcheck101);
        editor.putBoolean("name102", boxcheck102);
        editor.putBoolean("name103", boxcheck103);
        editor.putBoolean("name104", boxcheck104);
        editor.putBoolean("name105", boxcheck105);
        editor.putBoolean("name106", boxcheck106);
        editor.putBoolean("name107", boxcheck107);
        editor.putBoolean("name108", boxcheck108);
        editor.putBoolean("name109", boxcheck109);
        editor.putBoolean("name110", boxcheck110);
        editor.putBoolean("name111", boxcheck111);
        editor.putBoolean("name112", boxcheck112);
        editor.putBoolean("name113", boxcheck113);
        editor.putBoolean("name114", boxcheck114);
        editor.putBoolean("name115", boxcheck115);
        editor.putBoolean("name116", boxcheck116);
        editor.putBoolean("name117", boxcheck117);
        editor.putBoolean("name118", boxcheck118);
        editor.putBoolean("name119", boxcheck119);
        editor.putBoolean("name120", boxcheck120);
        editor.putBoolean("name121", boxcheck121);
        editor.putBoolean("name122", boxcheck122);
        editor.putBoolean("name123", boxcheck123);
        editor.putBoolean("name124", boxcheck124);
        editor.putBoolean("name125", boxcheck125);
        editor.putBoolean("name126", boxcheck126);
        editor.putBoolean("name127", boxcheck127);
        editor.putBoolean("name128", boxcheck128);
        editor.putBoolean("name129", boxcheck129);
        editor.putBoolean("name130", boxcheck130);
        editor.putBoolean("name131", boxcheck131);
        editor.putBoolean("name132", boxcheck132);
        editor.putBoolean("name133", boxcheck133);
        editor.putBoolean("name134", boxcheck134);
        editor.putBoolean("name135", boxcheck135);
        editor.putBoolean("name136", boxcheck136);
        editor.putBoolean("name137", boxcheck137);
        editor.putBoolean("name138", boxcheck138);
        editor.putBoolean("name139", boxcheck139);
        editor.putBoolean("name140", boxcheck140);
        editor.putBoolean("name141", boxcheck141);
        editor.putBoolean("name142", boxcheck142);
        editor.putBoolean("name143", boxcheck143);
        editor.putBoolean("name144", boxcheck144);
        editor.putBoolean("name145", boxcheck145);
        editor.putBoolean("name146", boxcheck146);
        editor.putBoolean("name147", boxcheck147);
        editor.putBoolean("name148", boxcheck148);
        editor.putBoolean("name149", boxcheck149);
        editor.putBoolean("name150", boxcheck150);
        editor.putBoolean("name151", boxcheck151);
        editor.putBoolean("name152", boxcheck152);
        editor.putBoolean("name153", boxcheck153);
        editor.putBoolean("name154", boxcheck154);
        editor.putBoolean("name155", boxcheck155);
        editor.putBoolean("name156", boxcheck156);
        editor.putBoolean("name157", boxcheck157);
        editor.putBoolean("name158", boxcheck158);
        editor.putBoolean("name159", boxcheck159);
        editor.putBoolean("name160", boxcheck160);
        editor.putBoolean("name161", boxcheck161);
        editor.putBoolean("name162", boxcheck162);
        editor.putBoolean("name163", boxcheck163);
        editor.putBoolean("name164", boxcheck164);
        editor.putBoolean("name165", boxcheck165);
        editor.putBoolean("name166", boxcheck166);
        editor.putBoolean("name167", boxcheck167);
        editor.putBoolean("name168", boxcheck168);
        editor.putBoolean("name169", boxcheck169);
        editor.putBoolean("name170", boxcheck170);
        editor.putBoolean("name171", boxcheck171);
        editor.putBoolean("name172", boxcheck172);
        editor.putBoolean("name173", boxcheck173);
        editor.putBoolean("name174", boxcheck174);
        editor.putBoolean("name175", boxcheck175);
        editor.putBoolean("name176", boxcheck176);
        editor.putBoolean("name177", boxcheck177);
        editor.putBoolean("name178", boxcheck178);
        editor.putBoolean("name179", boxcheck179);
        editor.putBoolean("name180", boxcheck180);
        editor.putBoolean("name181", boxcheck181);
        editor.putBoolean("name182", boxcheck182);
        editor.putBoolean("name183", boxcheck183);
        editor.putBoolean("name184", boxcheck184);
        editor.putBoolean("name185", boxcheck185);
        editor.putBoolean("name186", boxcheck186);
        editor.putBoolean("name187", boxcheck187);
        editor.putBoolean("name188", boxcheck188);
        editor.putBoolean("name189", boxcheck189);
        editor.putBoolean("name190", boxcheck190);
        editor.putBoolean("name191", boxcheck191);
        editor.putBoolean("name192", boxcheck192);
        editor.putBoolean("name193", boxcheck193);
        editor.putBoolean("name194", boxcheck194);
        editor.putBoolean("name195", boxcheck195);
        editor.putBoolean("name196", boxcheck196);
        editor.putBoolean("name197", boxcheck197);
        editor.putBoolean("name198", boxcheck198);
        editor.putBoolean("name199", boxcheck199);
        editor.putBoolean("name200", boxcheck200);
        editor.putBoolean("name201", boxcheck201);
        editor.putBoolean("name202", boxcheck202);
        editor.putBoolean("name203", boxcheck203);
        editor.putBoolean("name204", boxcheck204);
        editor.putBoolean("name205", boxcheck205);
        editor.putBoolean("name206", boxcheck206);
        editor.putBoolean("name207", boxcheck207);
        editor.putBoolean("name208", boxcheck208);
        editor.putBoolean("name209", boxcheck209);
        editor.putBoolean("name210", boxcheck210);
        editor.putBoolean("name211", boxcheck211);
        editor.putBoolean("name212", boxcheck212);
        editor.putBoolean("name213", boxcheck213);
        editor.putBoolean("name214", boxcheck214);
        editor.putBoolean("name215", boxcheck215);
        editor.putBoolean("name216", boxcheck216);
        editor.putBoolean("name217", boxcheck217);
        editor.putBoolean("name218", boxcheck218);
        editor.putBoolean("name219", boxcheck219);
        editor.putBoolean("name220", boxcheck220);
        editor.putBoolean("name221", boxcheck221);
        editor.putBoolean("name222", boxcheck222);
        editor.putBoolean("name223", boxcheck223);
        editor.putBoolean("name224", boxcheck224);
        editor.putBoolean("name225", boxcheck225);
        editor.putBoolean("name226", boxcheck226);
        editor.putBoolean("name227", boxcheck227);
        editor.putBoolean("name228", boxcheck228);
        editor.putBoolean("name229", boxcheck229);
        editor.putBoolean("name230", boxcheck230);
        editor.putBoolean("name231", boxcheck231);
        editor.putBoolean("name232", boxcheck232);
        editor.putBoolean("name233", boxcheck233);
        editor.putBoolean("name234", boxcheck234);
        editor.putBoolean("name235", boxcheck235);
        editor.putBoolean("name236", boxcheck236);
        editor.putBoolean("name237", boxcheck237);
        editor.putBoolean("name238", boxcheck238);
        editor.putBoolean("name239", boxcheck239);
        editor.putBoolean("name240", boxcheck240);
        editor.putBoolean("name241", boxcheck241);
        editor.putBoolean("name242", boxcheck242);
        editor.putBoolean("name243", boxcheck243);
        editor.putBoolean("name244", boxcheck244);
        editor.putBoolean("name245", boxcheck245);
        editor.putBoolean("name246", boxcheck246);
        editor.putBoolean("name247", boxcheck247);
        editor.putBoolean("name248", boxcheck248);
        editor.putBoolean("name249", boxcheck249);
        editor.putBoolean("name250", boxcheck250);
        editor.putBoolean("name251", boxcheck251);
        editor.putBoolean("name252", boxcheck252);
        editor.putBoolean("name253", boxcheck253);
        editor.putBoolean("name254", boxcheck254);
        editor.putBoolean("name255", boxcheck255);
        editor.putBoolean("name256", boxcheck256);
        editor.putBoolean("name257", boxcheck257);
        editor.putBoolean("name258", boxcheck258);
        editor.putBoolean("name259", boxcheck259);
        editor.putBoolean("name260", boxcheck260);
        editor.putBoolean("name261", boxcheck261);
        editor.putBoolean("name262", boxcheck262);
        editor.putBoolean("name263", boxcheck263);
        editor.putBoolean("name264", boxcheck264);
        editor.putBoolean("name265", boxcheck265);
        editor.putBoolean("name266", boxcheck266);
        editor.putBoolean("name267", boxcheck267);
        editor.putBoolean("name268", boxcheck268);
        editor.putBoolean("name269", boxcheck269);
        editor.putBoolean("name270", boxcheck270);
        editor.putBoolean("name271", boxcheck271);
        editor.putBoolean("name272", boxcheck272);
        editor.putBoolean("name273", boxcheck273);
        editor.putBoolean("name274", boxcheck274);
        editor.putBoolean("name275", boxcheck275);
        editor.putBoolean("name276", boxcheck276);
        editor.putBoolean("name277", boxcheck277);
        editor.putBoolean("name278", boxcheck278);
        editor.putBoolean("name279", boxcheck279);
        editor.putBoolean("name280", boxcheck280);
        editor.putBoolean("name281", boxcheck281);
        editor.putBoolean("name282", boxcheck282);
        editor.putBoolean("name283", boxcheck283);
        editor.putBoolean("name284", boxcheck284);
        editor.putBoolean("name285", boxcheck285);
        editor.putBoolean("name286", boxcheck286);
        editor.putBoolean("name287", boxcheck287);
        editor.putBoolean("name288", boxcheck288);
        editor.putBoolean("name289", boxcheck289);
        editor.putBoolean("name290", boxcheck290);
        editor.putBoolean("name291", boxcheck291);
        editor.putBoolean("name292", boxcheck292);
        editor.putBoolean("name293", boxcheck293);
        editor.putBoolean("name294", boxcheck294);
        editor.putBoolean("name295", boxcheck295);
        editor.putBoolean("name296", boxcheck296);
        editor.putBoolean("name297", boxcheck297);
        editor.putBoolean("name298", boxcheck298);
        editor.putBoolean("name299", boxcheck299);


        editor.commit();

        Log.d(TAG, "save: SAVE");
    }

    //load
    private void load() {
        SharedPreferences sharedPreferences = getSharedPreferences("MyData", MODE_PRIVATE);

        boolean box0 = sharedPreferences.getBoolean("name0", false);
        boolean box1 = sharedPreferences.getBoolean("name1", false);
        boolean box2 = sharedPreferences.getBoolean("name2", false);
        boolean box3 = sharedPreferences.getBoolean("name3", false);
        boolean box4 = sharedPreferences.getBoolean("name4", false);
        boolean box5 = sharedPreferences.getBoolean("name5", false);
        boolean box6 = sharedPreferences.getBoolean("name6", false);
        boolean box7 = sharedPreferences.getBoolean("name7", false);
        boolean box8 = sharedPreferences.getBoolean("name8", false);
        boolean box9 = sharedPreferences.getBoolean("name9", false);
        boolean box10 = sharedPreferences.getBoolean("name10", false);
        boolean box11 = sharedPreferences.getBoolean("name11", false);
        boolean box12 = sharedPreferences.getBoolean("name12", false);
        boolean box13 = sharedPreferences.getBoolean("name13", false);
        boolean box14 = sharedPreferences.getBoolean("name14", false);
        boolean box15 = sharedPreferences.getBoolean("name15", false);
        boolean box16 = sharedPreferences.getBoolean("name16", false);
        boolean box17 = sharedPreferences.getBoolean("name17", false);
        boolean box18 = sharedPreferences.getBoolean("name18", false);
        boolean box19 = sharedPreferences.getBoolean("name19", false);
        boolean box20 = sharedPreferences.getBoolean("name20", false);
        boolean box21 = sharedPreferences.getBoolean("name21", false);
        boolean box22 = sharedPreferences.getBoolean("name22", false);
        boolean box23 = sharedPreferences.getBoolean("name23", false);
        boolean box24 = sharedPreferences.getBoolean("name24", false);
        boolean box25 = sharedPreferences.getBoolean("name25", false);
        boolean box26 = sharedPreferences.getBoolean("name26", false);
        boolean box27 = sharedPreferences.getBoolean("name27", false);
        boolean box28 = sharedPreferences.getBoolean("name28", false);
        boolean box29 = sharedPreferences.getBoolean("name29", false);
        boolean box30 = sharedPreferences.getBoolean("name30", false);
        boolean box31 = sharedPreferences.getBoolean("name31", false);
        boolean box32 = sharedPreferences.getBoolean("name32", false);
        boolean box33 = sharedPreferences.getBoolean("name33", false);
        boolean box34 = sharedPreferences.getBoolean("name34", false);
        boolean box35 = sharedPreferences.getBoolean("name35", false);
        boolean box36 = sharedPreferences.getBoolean("name36", false);
        boolean box37 = sharedPreferences.getBoolean("name37", false);
        boolean box38 = sharedPreferences.getBoolean("name38", false);
        boolean box39 = sharedPreferences.getBoolean("name39", false);
        boolean box40 = sharedPreferences.getBoolean("name40", false);
        boolean box41 = sharedPreferences.getBoolean("name41", false);
        boolean box42 = sharedPreferences.getBoolean("name42", false);
        boolean box43 = sharedPreferences.getBoolean("name43", false);
        boolean box44 = sharedPreferences.getBoolean("name44", false);
        boolean box45 = sharedPreferences.getBoolean("name45", false);
        boolean box46 = sharedPreferences.getBoolean("name46", false);
        boolean box47 = sharedPreferences.getBoolean("name47", false);
        boolean box48 = sharedPreferences.getBoolean("name48", false);
        boolean box49 = sharedPreferences.getBoolean("name49", false);
        boolean box50 = sharedPreferences.getBoolean("name50", false);
        boolean box51 = sharedPreferences.getBoolean("name51", false);
        boolean box52 = sharedPreferences.getBoolean("name52", false);
        boolean box53 = sharedPreferences.getBoolean("name53", false);
        boolean box54 = sharedPreferences.getBoolean("name54", false);
        boolean box55 = sharedPreferences.getBoolean("name55", false);
        boolean box56 = sharedPreferences.getBoolean("name56", false);
        boolean box57 = sharedPreferences.getBoolean("name57", false);
        boolean box58 = sharedPreferences.getBoolean("name58", false);
        boolean box59 = sharedPreferences.getBoolean("name59", false);
        boolean box60 = sharedPreferences.getBoolean("name60", false);
        boolean box61 = sharedPreferences.getBoolean("name61", false);
        boolean box62 = sharedPreferences.getBoolean("name62", false);
        boolean box63 = sharedPreferences.getBoolean("name63", false);
        boolean box64 = sharedPreferences.getBoolean("name64", false);
        boolean box65 = sharedPreferences.getBoolean("name65", false);
        boolean box66 = sharedPreferences.getBoolean("name66", false);
        boolean box67 = sharedPreferences.getBoolean("name67", false);
        boolean box68 = sharedPreferences.getBoolean("name68", false);
        boolean box69 = sharedPreferences.getBoolean("name69", false);
        boolean box70 = sharedPreferences.getBoolean("name70", false);
        boolean box71 = sharedPreferences.getBoolean("name71", false);
        boolean box72 = sharedPreferences.getBoolean("name72", false);
        boolean box73 = sharedPreferences.getBoolean("name73", false);
        boolean box74 = sharedPreferences.getBoolean("name74", false);
        boolean box75 = sharedPreferences.getBoolean("name75", false);
        boolean box76 = sharedPreferences.getBoolean("name76", false);
        boolean box77 = sharedPreferences.getBoolean("name77", false);
        boolean box78 = sharedPreferences.getBoolean("name78", false);
        boolean box79 = sharedPreferences.getBoolean("name79", false);
        boolean box80 = sharedPreferences.getBoolean("name80", false);
        boolean box81 = sharedPreferences.getBoolean("name81", false);
        boolean box82 = sharedPreferences.getBoolean("name82", false);
        boolean box83 = sharedPreferences.getBoolean("name83", false);
        boolean box84 = sharedPreferences.getBoolean("name84", false);
        boolean box85 = sharedPreferences.getBoolean("name85", false);
        boolean box86 = sharedPreferences.getBoolean("name86", false);
        boolean box87 = sharedPreferences.getBoolean("name87", false);
        boolean box88 = sharedPreferences.getBoolean("name88", false);
        boolean box89 = sharedPreferences.getBoolean("name89", false);
        boolean box90 = sharedPreferences.getBoolean("name90", false);
        boolean box91 = sharedPreferences.getBoolean("name91 ", false);
        boolean box92 = sharedPreferences.getBoolean("name92 ", false);
        boolean box93 = sharedPreferences.getBoolean("name93 ", false);
        boolean box94 = sharedPreferences.getBoolean("name94 ", false);
        boolean box95 = sharedPreferences.getBoolean("name95 ", false);
        boolean box96 = sharedPreferences.getBoolean("name96 ", false);
        boolean box97 = sharedPreferences.getBoolean("name97 ", false);
        boolean box98 = sharedPreferences.getBoolean("name98 ", false);
        boolean box99 = sharedPreferences.getBoolean("name99 ", false);
        boolean box100 = sharedPreferences.getBoolean("name100", false);
        boolean box101 = sharedPreferences.getBoolean("name101", false);
        boolean box102 = sharedPreferences.getBoolean("name102", false);
        boolean box103 = sharedPreferences.getBoolean("name103", false);
        boolean box104 = sharedPreferences.getBoolean("name104", false);
        boolean box105 = sharedPreferences.getBoolean("name105", false);
        boolean box106 = sharedPreferences.getBoolean("name106", false);
        boolean box107 = sharedPreferences.getBoolean("name107", false);
        boolean box108 = sharedPreferences.getBoolean("name108", false);
        boolean box109 = sharedPreferences.getBoolean("name109", false);
        boolean box110 = sharedPreferences.getBoolean("name110", false);
        boolean box111 = sharedPreferences.getBoolean("name111", false);
        boolean box112 = sharedPreferences.getBoolean("name112", false);
        boolean box113 = sharedPreferences.getBoolean("name113", false);
        boolean box114 = sharedPreferences.getBoolean("name114", false);
        boolean box115 = sharedPreferences.getBoolean("name115", false);
        boolean box116 = sharedPreferences.getBoolean("name116", false);
        boolean box117 = sharedPreferences.getBoolean("name117", false);
        boolean box118 = sharedPreferences.getBoolean("name118", false);
        boolean box119 = sharedPreferences.getBoolean("name119", false);
        boolean box120 = sharedPreferences.getBoolean("name120", false);
        boolean box121 = sharedPreferences.getBoolean("name121", false);
        boolean box122 = sharedPreferences.getBoolean("name122", false);
        boolean box123 = sharedPreferences.getBoolean("name123", false);
        boolean box124 = sharedPreferences.getBoolean("name124", false);
        boolean box125 = sharedPreferences.getBoolean("name125", false);
        boolean box126 = sharedPreferences.getBoolean("name126", false);
        boolean box127 = sharedPreferences.getBoolean("name127", false);
        boolean box128 = sharedPreferences.getBoolean("name128", false);
        boolean box129 = sharedPreferences.getBoolean("name129", false);
        boolean box130 = sharedPreferences.getBoolean("name130", false);
        boolean box131 = sharedPreferences.getBoolean("name131", false);
        boolean box132 = sharedPreferences.getBoolean("name132", false);
        boolean box133 = sharedPreferences.getBoolean("name133", false);
        boolean box134 = sharedPreferences.getBoolean("name134", false);
        boolean box135 = sharedPreferences.getBoolean("name135", false);
        boolean box136 = sharedPreferences.getBoolean("name136", false);
        boolean box137 = sharedPreferences.getBoolean("name137", false);
        boolean box138 = sharedPreferences.getBoolean("name138", false);
        boolean box139 = sharedPreferences.getBoolean("name139", false);
        boolean box140 = sharedPreferences.getBoolean("name140", false);
        boolean box141 = sharedPreferences.getBoolean("name141", false);
        boolean box142 = sharedPreferences.getBoolean("name142", false);
        boolean box143 = sharedPreferences.getBoolean("name143", false);
        boolean box144 = sharedPreferences.getBoolean("name144", false);
        boolean box145 = sharedPreferences.getBoolean("name145", false);
        boolean box146 = sharedPreferences.getBoolean("name146", false);
        boolean box147 = sharedPreferences.getBoolean("name147", false);
        boolean box148 = sharedPreferences.getBoolean("name148", false);
        boolean box149 = sharedPreferences.getBoolean("name149", false);
        boolean box150 = sharedPreferences.getBoolean("name150", false);
        boolean box151 = sharedPreferences.getBoolean("name151", false);
        boolean box152 = sharedPreferences.getBoolean("name152", false);
        boolean box153 = sharedPreferences.getBoolean("name153", false);
        boolean box154 = sharedPreferences.getBoolean("name154", false);
        boolean box155 = sharedPreferences.getBoolean("name155", false);
        boolean box156 = sharedPreferences.getBoolean("name156", false);
        boolean box157 = sharedPreferences.getBoolean("name157", false);
        boolean box158 = sharedPreferences.getBoolean("name158", false);
        boolean box159 = sharedPreferences.getBoolean("name159", false);
        boolean box160 = sharedPreferences.getBoolean("name160", false);
        boolean box161 = sharedPreferences.getBoolean("name161", false);
        boolean box162 = sharedPreferences.getBoolean("name162", false);
        boolean box163 = sharedPreferences.getBoolean("name163", false);
        boolean box164 = sharedPreferences.getBoolean("name164", false);
        boolean box165 = sharedPreferences.getBoolean("name165", false);
        boolean box166 = sharedPreferences.getBoolean("name166", false);
        boolean box167 = sharedPreferences.getBoolean("name167", false);
        boolean box168 = sharedPreferences.getBoolean("name168", false);
        boolean box169 = sharedPreferences.getBoolean("name169", false);
        boolean box170 = sharedPreferences.getBoolean("name170", false);
        boolean box171 = sharedPreferences.getBoolean("name171", false);
        boolean box172 = sharedPreferences.getBoolean("name172", false);
        boolean box173 = sharedPreferences.getBoolean("name173", false);
        boolean box174 = sharedPreferences.getBoolean("name174", false);
        boolean box175 = sharedPreferences.getBoolean("name175", false);
        boolean box176 = sharedPreferences.getBoolean("name176", false);
        boolean box177 = sharedPreferences.getBoolean("name177", false);
        boolean box178 = sharedPreferences.getBoolean("name178", false);
        boolean box179 = sharedPreferences.getBoolean("name179", false);
        boolean box180 = sharedPreferences.getBoolean("name180", false);
        boolean box181 = sharedPreferences.getBoolean("name181", false);
        boolean box182 = sharedPreferences.getBoolean("name182", false);
        boolean box183 = sharedPreferences.getBoolean("name183", false);
        boolean box184 = sharedPreferences.getBoolean("name184", false);
        boolean box185 = sharedPreferences.getBoolean("name185", false);
        boolean box186 = sharedPreferences.getBoolean("name186", false);
        boolean box187 = sharedPreferences.getBoolean("name187", false);
        boolean box188 = sharedPreferences.getBoolean("name188", false);
        boolean box189 = sharedPreferences.getBoolean("name189", false);
        boolean box190 = sharedPreferences.getBoolean("name190", false);
        boolean box191 = sharedPreferences.getBoolean("name191", false);
        boolean box192 = sharedPreferences.getBoolean("name192", false);
        boolean box193 = sharedPreferences.getBoolean("name193", false);
        boolean box194 = sharedPreferences.getBoolean("name194", false);
        boolean box195 = sharedPreferences.getBoolean("name195", false);
        boolean box196 = sharedPreferences.getBoolean("name196", false);
        boolean box197 = sharedPreferences.getBoolean("name197", false);
        boolean box198 = sharedPreferences.getBoolean("name198", false);
        boolean box199 = sharedPreferences.getBoolean("name199", false);
        boolean box200 = sharedPreferences.getBoolean("name200", false);
        boolean box201 = sharedPreferences.getBoolean("name201", false);
        boolean box202 = sharedPreferences.getBoolean("name202", false);
        boolean box203 = sharedPreferences.getBoolean("name203", false);
        boolean box204 = sharedPreferences.getBoolean("name204", false);
        boolean box205 = sharedPreferences.getBoolean("name205", false);
        boolean box206 = sharedPreferences.getBoolean("name206", false);
        boolean box207 = sharedPreferences.getBoolean("name207", false);
        boolean box208 = sharedPreferences.getBoolean("name208", false);
        boolean box209 = sharedPreferences.getBoolean("name209", false);
        boolean box210 = sharedPreferences.getBoolean("name210", false);
        boolean box211 = sharedPreferences.getBoolean("name211", false);
        boolean box212 = sharedPreferences.getBoolean("name212", false);
        boolean box213 = sharedPreferences.getBoolean("name213", false);
        boolean box214 = sharedPreferences.getBoolean("name214", false);
        boolean box215 = sharedPreferences.getBoolean("name215", false);
        boolean box216 = sharedPreferences.getBoolean("name216", false);
        boolean box217 = sharedPreferences.getBoolean("name217", false);
        boolean box218 = sharedPreferences.getBoolean("name218", false);
        boolean box219 = sharedPreferences.getBoolean("name219", false);
        boolean box220 = sharedPreferences.getBoolean("name220", false);
        boolean box221 = sharedPreferences.getBoolean("name221", false);
        boolean box222 = sharedPreferences.getBoolean("name222", false);
        boolean box223 = sharedPreferences.getBoolean("name223", false);
        boolean box224 = sharedPreferences.getBoolean("name224", false);
        boolean box225 = sharedPreferences.getBoolean("name225", false);
        boolean box226 = sharedPreferences.getBoolean("name226", false);
        boolean box227 = sharedPreferences.getBoolean("name227", false);
        boolean box228 = sharedPreferences.getBoolean("name228", false);
        boolean box229 = sharedPreferences.getBoolean("name229", false);
        boolean box230 = sharedPreferences.getBoolean("name230", false);
        boolean box231 = sharedPreferences.getBoolean("name231", false);
        boolean box232 = sharedPreferences.getBoolean("name232", false);
        boolean box233 = sharedPreferences.getBoolean("name233", false);
        boolean box234 = sharedPreferences.getBoolean("name234", false);
        boolean box235 = sharedPreferences.getBoolean("name235", false);
        boolean box236 = sharedPreferences.getBoolean("name236", false);
        boolean box237 = sharedPreferences.getBoolean("name237", false);
        boolean box238 = sharedPreferences.getBoolean("name238", false);
        boolean box239 = sharedPreferences.getBoolean("name239", false);
        boolean box240 = sharedPreferences.getBoolean("name240", false);
        boolean box241 = sharedPreferences.getBoolean("name241", false);
        boolean box242 = sharedPreferences.getBoolean("name242", false);
        boolean box243 = sharedPreferences.getBoolean("name243", false);
        boolean box244 = sharedPreferences.getBoolean("name244", false);
        boolean box245 = sharedPreferences.getBoolean("name245", false);
        boolean box246 = sharedPreferences.getBoolean("name246", false);
        boolean box247 = sharedPreferences.getBoolean("name247", false);
        boolean box248 = sharedPreferences.getBoolean("name248", false);
        boolean box249 = sharedPreferences.getBoolean("name249", false);
        boolean box250 = sharedPreferences.getBoolean("name250", false);
        boolean box251 = sharedPreferences.getBoolean("name251", false);
        boolean box252 = sharedPreferences.getBoolean("name252", false);
        boolean box253 = sharedPreferences.getBoolean("name253", false);
        boolean box254 = sharedPreferences.getBoolean("name254", false);
        boolean box255 = sharedPreferences.getBoolean("name255", false);
        boolean box256 = sharedPreferences.getBoolean("name256", false);
        boolean box257 = sharedPreferences.getBoolean("name257", false);
        boolean box258 = sharedPreferences.getBoolean("name258", false);
        boolean box259 = sharedPreferences.getBoolean("name259", false);
        boolean box260 = sharedPreferences.getBoolean("name260", false);
        boolean box261 = sharedPreferences.getBoolean("name261", false);
        boolean box262 = sharedPreferences.getBoolean("name262", false);
        boolean box263 = sharedPreferences.getBoolean("name263", false);
        boolean box264 = sharedPreferences.getBoolean("name264", false);
        boolean box265 = sharedPreferences.getBoolean("name265", false);
        boolean box266 = sharedPreferences.getBoolean("name266", false);
        boolean box267 = sharedPreferences.getBoolean("name267", false);
        boolean box268 = sharedPreferences.getBoolean("name268", false);
        boolean box269 = sharedPreferences.getBoolean("name269", false);
        boolean box270 = sharedPreferences.getBoolean("name270", false);
        boolean box271 = sharedPreferences.getBoolean("name271", false);
        boolean box272 = sharedPreferences.getBoolean("name272", false);
        boolean box273 = sharedPreferences.getBoolean("name273", false);
        boolean box274 = sharedPreferences.getBoolean("name274", false);
        boolean box275 = sharedPreferences.getBoolean("name275", false);
        boolean box276 = sharedPreferences.getBoolean("name276", false);
        boolean box277 = sharedPreferences.getBoolean("name277", false);
        boolean box278 = sharedPreferences.getBoolean("name278", false);
        boolean box279 = sharedPreferences.getBoolean("name279", false);
        boolean box280 = sharedPreferences.getBoolean("name280", false);
        boolean box281 = sharedPreferences.getBoolean("name281", false);
        boolean box282 = sharedPreferences.getBoolean("name282", false);
        boolean box283 = sharedPreferences.getBoolean("name283", false);
        boolean box284 = sharedPreferences.getBoolean("name284", false);
        boolean box285 = sharedPreferences.getBoolean("name285", false);
        boolean box286 = sharedPreferences.getBoolean("name286", false);
        boolean box287 = sharedPreferences.getBoolean("name287", false);
        boolean box288 = sharedPreferences.getBoolean("name288", false);
        boolean box289 = sharedPreferences.getBoolean("name289", false);
        boolean box290 = sharedPreferences.getBoolean("name290", false);
        boolean box291 = sharedPreferences.getBoolean("name291", false);
        boolean box292 = sharedPreferences.getBoolean("name292", false);
        boolean box293 = sharedPreferences.getBoolean("name293", false);
        boolean box294 = sharedPreferences.getBoolean("name294", false);
        boolean box295 = sharedPreferences.getBoolean("name295", false);
        boolean box296 = sharedPreferences.getBoolean("name296", false);
        boolean box297 = sharedPreferences.getBoolean("name297", false);
        boolean box298 = sharedPreferences.getBoolean("name298", false);
        boolean box299 = sharedPreferences.getBoolean("name299", false);
        boolean box300 = sharedPreferences.getBoolean("name300", false);


        boxcheck0 = box0;
        boxcheck1 = box1;
        boxcheck2 = box2;
        boxcheck3 = box3;
        boxcheck4 = box4;
        boxcheck5 = box5;
        boxcheck6 = box6;
        boxcheck7 = box7;
        boxcheck8 = box8;
        boxcheck9 = box9;
        boxcheck10 = box10;
        boxcheck11 = box11;
        boxcheck12 = box12;
        boxcheck13 = box13;
        boxcheck14 = box14;
        boxcheck15 = box15;
        boxcheck16 = box16;
        boxcheck17 = box17;
        boxcheck18 = box18;
        boxcheck19 = box19;
        boxcheck20 = box20;
        boxcheck21 = box21;
        boxcheck22 = box22;
        boxcheck23 = box23;
        boxcheck24 = box24;
        boxcheck25 = box25;
        boxcheck26 = box26;
        boxcheck27 = box27;
        boxcheck28 = box28;
        boxcheck29 = box29;
        boxcheck30 = box30;
        boxcheck31 = box31;
        boxcheck32 = box32;
        boxcheck33 = box33;
        boxcheck34 = box34;
        boxcheck35 = box35;
        boxcheck36 = box36;
        boxcheck37 = box37;
        boxcheck38 = box38;
        boxcheck39 = box39;
        boxcheck40 = box40;
        boxcheck41 = box41;
        boxcheck42 = box42;
        boxcheck43 = box43;
        boxcheck44 = box44;
        boxcheck45 = box45;
        boxcheck46 = box46;
        boxcheck47 = box47;
        boxcheck48 = box48;
        boxcheck49 = box49;
        boxcheck50 = box50;
        boxcheck51 = box51;
        boxcheck52 = box52;
        boxcheck53 = box53;
        boxcheck54 = box54;
        boxcheck55 = box55;
        boxcheck56 = box56;
        boxcheck57 = box57;
        boxcheck58 = box58;
        boxcheck59 = box59;
        boxcheck60 = box60;
        boxcheck61 = box61;
        boxcheck62 = box62;
        boxcheck63 = box63;
        boxcheck64 = box64;
        boxcheck65 = box65;
        boxcheck66 = box66;
        boxcheck67 = box67;
        boxcheck68 = box68;
        boxcheck69 = box69;
        boxcheck70 = box70;
        boxcheck71 = box71;
        boxcheck72 = box72;
        boxcheck73 = box73;
        boxcheck74 = box74;
        boxcheck75 = box75;
        boxcheck76 = box76;
        boxcheck77 = box77;
        boxcheck78 = box78;
        boxcheck79 = box79;
        boxcheck80 = box80;
        boxcheck81 = box81;
        boxcheck82 = box82;
        boxcheck83 = box83;
        boxcheck84 = box84;
        boxcheck85 = box85;
        boxcheck86 = box86;
        boxcheck87 = box87;
        boxcheck88 = box88;
        boxcheck89 = box89;
        boxcheck90 = box90;
        boxcheck91 = box91;
        boxcheck92 = box92;
        boxcheck93 = box93;
        boxcheck94 = box94;
        boxcheck95 = box95;
        boxcheck96 = box96;
        boxcheck97 = box97;
        boxcheck98 = box98;
        boxcheck99 = box99;
        boxcheck100 = box100;
        boxcheck100 = box100;
        boxcheck101 = box101;
        boxcheck102 = box102;
        boxcheck103 = box103;
        boxcheck104 = box104;
        boxcheck105 = box105;
        boxcheck106 = box106;
        boxcheck107 = box107;
        boxcheck108 = box108;
        boxcheck109 = box109;
        boxcheck110 = box110;
        boxcheck111 = box111;
        boxcheck112 = box112;
        boxcheck113 = box113;
        boxcheck114 = box114;
        boxcheck115 = box115;
        boxcheck116 = box116;
        boxcheck117 = box117;
        boxcheck118 = box118;
        boxcheck119 = box119;
        boxcheck120 = box120;
        boxcheck121 = box121;
        boxcheck122 = box122;
        boxcheck123 = box123;
        boxcheck124 = box124;
        boxcheck125 = box125;
        boxcheck126 = box126;
        boxcheck127 = box127;
        boxcheck128 = box128;
        boxcheck129 = box129;
        boxcheck130 = box130;
        boxcheck131 = box131;
        boxcheck132 = box132;
        boxcheck133 = box133;
        boxcheck134 = box134;
        boxcheck135 = box135;
        boxcheck136 = box136;
        boxcheck137 = box137;
        boxcheck138 = box138;
        boxcheck139 = box139;
        boxcheck140 = box140;
        boxcheck141 = box141;
        boxcheck142 = box142;
        boxcheck143 = box143;
        boxcheck144 = box144;
        boxcheck145 = box145;
        boxcheck146 = box146;
        boxcheck147 = box147;
        boxcheck148 = box148;
        boxcheck149 = box149;
        boxcheck150 = box150;
        boxcheck151 = box151;
        boxcheck152 = box152;
        boxcheck153 = box153;
        boxcheck154 = box154;
        boxcheck155 = box155;
        boxcheck156 = box156;
        boxcheck157 = box157;
        boxcheck158 = box158;
        boxcheck159 = box159;
        boxcheck160 = box160;
        boxcheck161 = box161;
        boxcheck162 = box162;
        boxcheck163 = box163;
        boxcheck164 = box164;
        boxcheck165 = box165;
        boxcheck166 = box166;
        boxcheck167 = box167;
        boxcheck168 = box168;
        boxcheck169 = box169;
        boxcheck170 = box170;
        boxcheck171 = box171;
        boxcheck172 = box172;
        boxcheck173 = box173;
        boxcheck174 = box174;
        boxcheck175 = box175;
        boxcheck176 = box176;
        boxcheck177 = box177;
        boxcheck178 = box178;
        boxcheck179 = box179;
        boxcheck180 = box180;
        boxcheck181 = box181;
        boxcheck182 = box182;
        boxcheck183 = box183;
        boxcheck184 = box184;
        boxcheck185 = box185;
        boxcheck186 = box186;
        boxcheck187 = box187;
        boxcheck188 = box188;
        boxcheck189 = box189;
        boxcheck190 = box190;
        boxcheck191 = box191;
        boxcheck192 = box192;
        boxcheck193 = box193;
        boxcheck194 = box194;
        boxcheck195 = box195;
        boxcheck196 = box196;
        boxcheck197 = box197;
        boxcheck198 = box198;
        boxcheck199 = box199;
        boxcheck200 = box200;
        boxcheck201 = box201;
        boxcheck202 = box202;
        boxcheck203 = box203;
        boxcheck204 = box204;
        boxcheck205 = box205;
        boxcheck206 = box206;
        boxcheck207 = box207;
        boxcheck208 = box208;
        boxcheck209 = box209;
        boxcheck210 = box210;
        boxcheck211 = box211;
        boxcheck212 = box212;
        boxcheck213 = box213;
        boxcheck214 = box214;
        boxcheck215 = box215;
        boxcheck216 = box216;
        boxcheck217 = box217;
        boxcheck218 = box218;
        boxcheck219 = box219;
        boxcheck220 = box220;
        boxcheck221 = box221;
        boxcheck222 = box222;
        boxcheck223 = box223;
        boxcheck224 = box224;
        boxcheck225 = box225;
        boxcheck226 = box226;
        boxcheck227 = box227;
        boxcheck228 = box228;
        boxcheck229 = box229;
        boxcheck230 = box230;
        boxcheck231 = box231;
        boxcheck232 = box232;
        boxcheck233 = box233;
        boxcheck234 = box234;
        boxcheck235 = box235;
        boxcheck236 = box236;
        boxcheck237 = box237;
        boxcheck238 = box238;
        boxcheck239 = box239;
        boxcheck240 = box240;
        boxcheck241 = box241;
        boxcheck242 = box242;
        boxcheck243 = box243;
        boxcheck244 = box244;
        boxcheck245 = box245;
        boxcheck246 = box246;
        boxcheck247 = box247;
        boxcheck248 = box248;
        boxcheck249 = box249;
        boxcheck250 = box250;
        boxcheck251 = box251;
        boxcheck252 = box252;
        boxcheck253 = box253;
        boxcheck254 = box254;
        boxcheck255 = box255;
        boxcheck256 = box256;
        boxcheck257 = box257;
        boxcheck258 = box258;
        boxcheck259 = box259;
        boxcheck260 = box260;
        boxcheck261 = box261;
        boxcheck262 = box262;
        boxcheck263 = box263;
        boxcheck264 = box264;
        boxcheck265 = box265;
        boxcheck266 = box266;
        boxcheck267 = box267;
        boxcheck268 = box268;
        boxcheck269 = box269;
        boxcheck270 = box270;
        boxcheck271 = box271;
        boxcheck272 = box272;
        boxcheck273 = box273;
        boxcheck274 = box274;
        boxcheck275 = box275;
        boxcheck276 = box276;
        boxcheck277 = box277;
        boxcheck278 = box278;
        boxcheck279 = box279;
        boxcheck280 = box280;
        boxcheck281 = box281;
        boxcheck282 = box282;
        boxcheck283 = box283;
        boxcheck284 = box284;
        boxcheck285 = box285;
        boxcheck286 = box286;
        boxcheck287 = box287;
        boxcheck288 = box288;
        boxcheck289 = box289;
        boxcheck290 = box290;
        boxcheck291 = box291;
        boxcheck292 = box292;
        boxcheck293 = box293;
        boxcheck294 = box294;
        boxcheck295 = box295;
        boxcheck296 = box296;
        boxcheck297 = box297;
        boxcheck298 = box298;
        boxcheck299 = box299;
        boxcheck300 = box300;

        Log.d(TAG, "load: LOADED");
    }

    //update
    private void update() {
        Log.d(TAG, "update:UPDATED:");
        if (boxcheck0) mercmissionsLayout.setItemChecked(0, true);
        if (boxcheck1) mercmissionsLayout.setItemChecked(1, true);
        if (boxcheck2) mercmissionsLayout.setItemChecked(2, true);
        if (boxcheck3) mercmissionsLayout.setItemChecked(3, true);
        if (boxcheck4) mercmissionsLayout.setItemChecked(4, true);
        if (boxcheck5) mercmissionsLayout.setItemChecked(5, true);
        if (boxcheck6) mercmissionsLayout.setItemChecked(6, true);
        if (boxcheck7) mercmissionsLayout.setItemChecked(7, true);
        if (boxcheck8) mercmissionsLayout.setItemChecked(8, true);
        if (boxcheck9) mercmissionsLayout.setItemChecked(9, true);
        if (boxcheck10) mercmissionsLayout.setItemChecked(10, true);
        if (boxcheck11) mercmissionsLayout.setItemChecked(11, true);
        if (boxcheck12) mercmissionsLayout.setItemChecked(12, true);
        if (boxcheck13) mercmissionsLayout.setItemChecked(13, true);
        if (boxcheck14) mercmissionsLayout.setItemChecked(14, true);
        if (boxcheck15) mercmissionsLayout.setItemChecked(15, true);
        if (boxcheck16) mercmissionsLayout.setItemChecked(16, true);
        if (boxcheck17) mercmissionsLayout.setItemChecked(17, true);
        if (boxcheck18) mercmissionsLayout.setItemChecked(18, true);
        if (boxcheck19) mercmissionsLayout.setItemChecked(19, true);
        if (boxcheck20) mercmissionsLayout.setItemChecked(20, true);
        if (boxcheck21) mercmissionsLayout.setItemChecked(21, true);
        if (boxcheck22) mercmissionsLayout.setItemChecked(22, true);
        if (boxcheck23) mercmissionsLayout.setItemChecked(23, true);
        if (boxcheck24) mercmissionsLayout.setItemChecked(24, true);
        if (boxcheck25) mercmissionsLayout.setItemChecked(25, true);
        if (boxcheck26) mercmissionsLayout.setItemChecked(26, true);
        if (boxcheck27) mercmissionsLayout.setItemChecked(27, true);
        if (boxcheck28) mercmissionsLayout.setItemChecked(28, true);
        if (boxcheck29) mercmissionsLayout.setItemChecked(29, true);
        if (boxcheck30) mercmissionsLayout.setItemChecked(30, true);
        if (boxcheck31) mercmissionsLayout.setItemChecked(31, true);
        if (boxcheck32) mercmissionsLayout.setItemChecked(32, true);
        if (boxcheck33) mercmissionsLayout.setItemChecked(33, true);
        if (boxcheck34) mercmissionsLayout.setItemChecked(34, true);
        if (boxcheck35) mercmissionsLayout.setItemChecked(35, true);
        if (boxcheck36) mercmissionsLayout.setItemChecked(36, true);
        if (boxcheck37) mercmissionsLayout.setItemChecked(37, true);
        if (boxcheck38) mercmissionsLayout.setItemChecked(38, true);
        if (boxcheck39) mercmissionsLayout.setItemChecked(39, true);
        if (boxcheck40) mercmissionsLayout.setItemChecked(40, true);
        if (boxcheck41) mercmissionsLayout.setItemChecked(41, true);
        if (boxcheck42) mercmissionsLayout.setItemChecked(42, true);
        if (boxcheck43) mercmissionsLayout.setItemChecked(43, true);
        if (boxcheck44) mercmissionsLayout.setItemChecked(44, true);
        if (boxcheck45) mercmissionsLayout.setItemChecked(45, true);
        if (boxcheck46) mercmissionsLayout.setItemChecked(46, true);
        if (boxcheck47) mercmissionsLayout.setItemChecked(47, true);
        if (boxcheck48) mercmissionsLayout.setItemChecked(48, true);
        if (boxcheck49) mercmissionsLayout.setItemChecked(49, true);
        if (boxcheck50) mercmissionsLayout.setItemChecked(50, true);
        if (boxcheck51) mercmissionsLayout.setItemChecked(51, true);
        if (boxcheck52) mercmissionsLayout.setItemChecked(52, true);
        if (boxcheck53) mercmissionsLayout.setItemChecked(53, true);
        if (boxcheck54) mercmissionsLayout.setItemChecked(54, true);
        if (boxcheck55) mercmissionsLayout.setItemChecked(55, true);
        if (boxcheck56) mercmissionsLayout.setItemChecked(56, true);
        if (boxcheck57) mercmissionsLayout.setItemChecked(57, true);
        if (boxcheck58) mercmissionsLayout.setItemChecked(58, true);
        if (boxcheck59) mercmissionsLayout.setItemChecked(59, true);
        if (boxcheck60) mercmissionsLayout.setItemChecked(60, true);
        if (boxcheck61) mercmissionsLayout.setItemChecked(61, true);
        if (boxcheck62) mercmissionsLayout.setItemChecked(62, true);
        if (boxcheck63) mercmissionsLayout.setItemChecked(63, true);
        if (boxcheck64) mercmissionsLayout.setItemChecked(64, true);
        if (boxcheck65) mercmissionsLayout.setItemChecked(65, true);
        if (boxcheck66) mercmissionsLayout.setItemChecked(66, true);
        if (boxcheck67) mercmissionsLayout.setItemChecked(67, true);
        if (boxcheck68) mercmissionsLayout.setItemChecked(68, true);
        if (boxcheck69) mercmissionsLayout.setItemChecked(69, true);
        if (boxcheck70) mercmissionsLayout.setItemChecked(70, true);
        if (boxcheck71) mercmissionsLayout.setItemChecked(71, true);
        if (boxcheck72) mercmissionsLayout.setItemChecked(72, true);
        if (boxcheck73) mercmissionsLayout.setItemChecked(73, true);
        if (boxcheck74) mercmissionsLayout.setItemChecked(74, true);
        if (boxcheck75) mercmissionsLayout.setItemChecked(75, true);
        if (boxcheck76) mercmissionsLayout.setItemChecked(76, true);
        if (boxcheck77) mercmissionsLayout.setItemChecked(77, true);
        if (boxcheck78) mercmissionsLayout.setItemChecked(78, true);
        if (boxcheck79) mercmissionsLayout.setItemChecked(79, true);
        if (boxcheck80) mercmissionsLayout.setItemChecked(80, true);
        if (boxcheck81) mercmissionsLayout.setItemChecked(81, true);
        if (boxcheck82) mercmissionsLayout.setItemChecked(82, true);
        if (boxcheck83) mercmissionsLayout.setItemChecked(83, true);
        if (boxcheck84) mercmissionsLayout.setItemChecked(84, true);
        if (boxcheck85) mercmissionsLayout.setItemChecked(85, true);
        if (boxcheck86) mercmissionsLayout.setItemChecked(86, true);
        if (boxcheck87) mercmissionsLayout.setItemChecked(87, true);
        if (boxcheck88) mercmissionsLayout.setItemChecked(88, true);
        if (boxcheck89) mercmissionsLayout.setItemChecked(89, true);
        if (boxcheck90) mercmissionsLayout.setItemChecked(90, true);
        if (boxcheck91) mercmissionsLayout.setItemChecked(91, true);
        if (boxcheck92) mercmissionsLayout.setItemChecked(92, true);
        if (boxcheck93) mercmissionsLayout.setItemChecked(93, true);
        if (boxcheck94) mercmissionsLayout.setItemChecked(94, true);
        if (boxcheck95) mercmissionsLayout.setItemChecked(95, true);
        if (boxcheck96) mercmissionsLayout.setItemChecked(96, true);
        if (boxcheck97) mercmissionsLayout.setItemChecked(97, true);
        if (boxcheck98) mercmissionsLayout.setItemChecked(98, true);
        if (boxcheck99) mercmissionsLayout.setItemChecked(99, true);
        if (boxcheck100) mercmissionsLayout.setItemChecked(100, true);
        if (boxcheck100) mercmissionsLayout.setItemChecked(100, true);
        if (boxcheck101) mercmissionsLayout.setItemChecked(101, true);
        if (boxcheck102) mercmissionsLayout.setItemChecked(102, true);
        if (boxcheck103) mercmissionsLayout.setItemChecked(103, true);
        if (boxcheck104) mercmissionsLayout.setItemChecked(104, true);
        if (boxcheck105) mercmissionsLayout.setItemChecked(105, true);
        if (boxcheck106) mercmissionsLayout.setItemChecked(106, true);
        if (boxcheck107) mercmissionsLayout.setItemChecked(107, true);
        if (boxcheck108) mercmissionsLayout.setItemChecked(108, true);
        if (boxcheck109) mercmissionsLayout.setItemChecked(109, true);
        if (boxcheck110) mercmissionsLayout.setItemChecked(110, true);
        if (boxcheck111) mercmissionsLayout.setItemChecked(111, true);
        if (boxcheck112) mercmissionsLayout.setItemChecked(112, true);
        if (boxcheck113) mercmissionsLayout.setItemChecked(113, true);
        if (boxcheck114) mercmissionsLayout.setItemChecked(114, true);
        if (boxcheck115) mercmissionsLayout.setItemChecked(115, true);
        if (boxcheck116) mercmissionsLayout.setItemChecked(116, true);
        if (boxcheck117) mercmissionsLayout.setItemChecked(117, true);
        if (boxcheck118) mercmissionsLayout.setItemChecked(118, true);
        if (boxcheck119) mercmissionsLayout.setItemChecked(119, true);
        if (boxcheck120) mercmissionsLayout.setItemChecked(120, true);
        if (boxcheck121) mercmissionsLayout.setItemChecked(121, true);
        if (boxcheck122) mercmissionsLayout.setItemChecked(122, true);
        if (boxcheck123) mercmissionsLayout.setItemChecked(123, true);
        if (boxcheck124) mercmissionsLayout.setItemChecked(124, true);
        if (boxcheck125) mercmissionsLayout.setItemChecked(125, true);
        if (boxcheck126) mercmissionsLayout.setItemChecked(126, true);
        if (boxcheck127) mercmissionsLayout.setItemChecked(127, true);
        if (boxcheck128) mercmissionsLayout.setItemChecked(128, true);
        if (boxcheck129) mercmissionsLayout.setItemChecked(129, true);
        if (boxcheck130) mercmissionsLayout.setItemChecked(130, true);
        if (boxcheck131) mercmissionsLayout.setItemChecked(131, true);
        if (boxcheck132) mercmissionsLayout.setItemChecked(132, true);
        if (boxcheck133) mercmissionsLayout.setItemChecked(133, true);
        if (boxcheck134) mercmissionsLayout.setItemChecked(134, true);
        if (boxcheck135) mercmissionsLayout.setItemChecked(135, true);
        if (boxcheck136) mercmissionsLayout.setItemChecked(136, true);
        if (boxcheck137) mercmissionsLayout.setItemChecked(137, true);
        if (boxcheck138) mercmissionsLayout.setItemChecked(138, true);
        if (boxcheck139) mercmissionsLayout.setItemChecked(139, true);
        if (boxcheck140) mercmissionsLayout.setItemChecked(140, true);
        if (boxcheck141) mercmissionsLayout.setItemChecked(141, true);
        if (boxcheck142) mercmissionsLayout.setItemChecked(142, true);
        if (boxcheck143) mercmissionsLayout.setItemChecked(143, true);
        if (boxcheck144) mercmissionsLayout.setItemChecked(144, true);
        if (boxcheck145) mercmissionsLayout.setItemChecked(145, true);
        if (boxcheck146) mercmissionsLayout.setItemChecked(146, true);
        if (boxcheck147) mercmissionsLayout.setItemChecked(147, true);
        if (boxcheck148) mercmissionsLayout.setItemChecked(148, true);
        if (boxcheck149) mercmissionsLayout.setItemChecked(149, true);
        if (boxcheck150) mercmissionsLayout.setItemChecked(150, true);
        if (boxcheck151) mercmissionsLayout.setItemChecked(151, true);
        if (boxcheck152) mercmissionsLayout.setItemChecked(152, true);
        if (boxcheck153) mercmissionsLayout.setItemChecked(153, true);
        if (boxcheck154) mercmissionsLayout.setItemChecked(154, true);
        if (boxcheck155) mercmissionsLayout.setItemChecked(155, true);
        if (boxcheck156) mercmissionsLayout.setItemChecked(156, true);
        if (boxcheck157) mercmissionsLayout.setItemChecked(157, true);
        if (boxcheck158) mercmissionsLayout.setItemChecked(158, true);
        if (boxcheck159) mercmissionsLayout.setItemChecked(159, true);
        if (boxcheck160) mercmissionsLayout.setItemChecked(160, true);
        if (boxcheck161) mercmissionsLayout.setItemChecked(161, true);
        if (boxcheck162) mercmissionsLayout.setItemChecked(162, true);
        if (boxcheck163) mercmissionsLayout.setItemChecked(163, true);
        if (boxcheck164) mercmissionsLayout.setItemChecked(164, true);
        if (boxcheck165) mercmissionsLayout.setItemChecked(165, true);
        if (boxcheck166) mercmissionsLayout.setItemChecked(166, true);
        if (boxcheck167) mercmissionsLayout.setItemChecked(167, true);
        if (boxcheck168) mercmissionsLayout.setItemChecked(168, true);
        if (boxcheck169) mercmissionsLayout.setItemChecked(169, true);
        if (boxcheck170) mercmissionsLayout.setItemChecked(170, true);
        if (boxcheck171) mercmissionsLayout.setItemChecked(171, true);
        if (boxcheck172) mercmissionsLayout.setItemChecked(172, true);
        if (boxcheck173) mercmissionsLayout.setItemChecked(173, true);
        if (boxcheck174) mercmissionsLayout.setItemChecked(174, true);
        if (boxcheck175) mercmissionsLayout.setItemChecked(175, true);
        if (boxcheck176) mercmissionsLayout.setItemChecked(176, true);
        if (boxcheck177) mercmissionsLayout.setItemChecked(177, true);
        if (boxcheck178) mercmissionsLayout.setItemChecked(178, true);
        if (boxcheck179) mercmissionsLayout.setItemChecked(179, true);
        if (boxcheck180) mercmissionsLayout.setItemChecked(180, true);
        if (boxcheck181) mercmissionsLayout.setItemChecked(181, true);
        if (boxcheck182) mercmissionsLayout.setItemChecked(182, true);
        if (boxcheck183) mercmissionsLayout.setItemChecked(183, true);
        if (boxcheck184) mercmissionsLayout.setItemChecked(184, true);
        if (boxcheck185) mercmissionsLayout.setItemChecked(185, true);
        if (boxcheck186) mercmissionsLayout.setItemChecked(186, true);
        if (boxcheck187) mercmissionsLayout.setItemChecked(187, true);
        if (boxcheck188) mercmissionsLayout.setItemChecked(188, true);
        if (boxcheck189) mercmissionsLayout.setItemChecked(189, true);
        if (boxcheck190) mercmissionsLayout.setItemChecked(190, true);
        if (boxcheck191) mercmissionsLayout.setItemChecked(191, true);
        if (boxcheck192) mercmissionsLayout.setItemChecked(192, true);
        if (boxcheck193) mercmissionsLayout.setItemChecked(193, true);
        if (boxcheck194) mercmissionsLayout.setItemChecked(194, true);
        if (boxcheck195) mercmissionsLayout.setItemChecked(195, true);
        if (boxcheck196) mercmissionsLayout.setItemChecked(196, true);
        if (boxcheck197) mercmissionsLayout.setItemChecked(197, true);
        if (boxcheck198) mercmissionsLayout.setItemChecked(198, true);
        if (boxcheck199) mercmissionsLayout.setItemChecked(199, true);
        if (boxcheck200) mercmissionsLayout.setItemChecked(200, true);
        if (boxcheck201) mercmissionsLayout.setItemChecked(201, true);
        if (boxcheck202) mercmissionsLayout.setItemChecked(202, true);
        if (boxcheck203) mercmissionsLayout.setItemChecked(203, true);
        if (boxcheck204) mercmissionsLayout.setItemChecked(204, true);
        if (boxcheck205) mercmissionsLayout.setItemChecked(205, true);
        if (boxcheck206) mercmissionsLayout.setItemChecked(206, true);
        if (boxcheck207) mercmissionsLayout.setItemChecked(207, true);
        if (boxcheck208) mercmissionsLayout.setItemChecked(208, true);
        if (boxcheck209) mercmissionsLayout.setItemChecked(209, true);
        if (boxcheck210) mercmissionsLayout.setItemChecked(210, true);
        if (boxcheck211) mercmissionsLayout.setItemChecked(211, true);
        if (boxcheck212) mercmissionsLayout.setItemChecked(212, true);
        if (boxcheck213) mercmissionsLayout.setItemChecked(213, true);
        if (boxcheck214) mercmissionsLayout.setItemChecked(214, true);
        if (boxcheck215) mercmissionsLayout.setItemChecked(215, true);
        if (boxcheck216) mercmissionsLayout.setItemChecked(216, true);
        if (boxcheck217) mercmissionsLayout.setItemChecked(217, true);
        if (boxcheck218) mercmissionsLayout.setItemChecked(218, true);
        if (boxcheck219) mercmissionsLayout.setItemChecked(219, true);
        if (boxcheck220) mercmissionsLayout.setItemChecked(220, true);
        if (boxcheck221) mercmissionsLayout.setItemChecked(221, true);
        if (boxcheck222) mercmissionsLayout.setItemChecked(222, true);
        if (boxcheck223) mercmissionsLayout.setItemChecked(223, true);
        if (boxcheck224) mercmissionsLayout.setItemChecked(224, true);
        if (boxcheck225) mercmissionsLayout.setItemChecked(225, true);
        if (boxcheck226) mercmissionsLayout.setItemChecked(226, true);
        if (boxcheck227) mercmissionsLayout.setItemChecked(227, true);
        if (boxcheck228) mercmissionsLayout.setItemChecked(228, true);
        if (boxcheck229) mercmissionsLayout.setItemChecked(229, true);
        if (boxcheck230) mercmissionsLayout.setItemChecked(230, true);
        if (boxcheck231) mercmissionsLayout.setItemChecked(231, true);
        if (boxcheck232) mercmissionsLayout.setItemChecked(232, true);
        if (boxcheck233) mercmissionsLayout.setItemChecked(233, true);
        if (boxcheck234) mercmissionsLayout.setItemChecked(234, true);
        if (boxcheck235) mercmissionsLayout.setItemChecked(235, true);
        if (boxcheck236) mercmissionsLayout.setItemChecked(236, true);
        if (boxcheck237) mercmissionsLayout.setItemChecked(237, true);
        if (boxcheck238) mercmissionsLayout.setItemChecked(238, true);
        if (boxcheck239) mercmissionsLayout.setItemChecked(239, true);
        if (boxcheck240) mercmissionsLayout.setItemChecked(240, true);
        if (boxcheck241) mercmissionsLayout.setItemChecked(241, true);
        if (boxcheck242) mercmissionsLayout.setItemChecked(242, true);
        if (boxcheck243) mercmissionsLayout.setItemChecked(243, true);
        if (boxcheck244) mercmissionsLayout.setItemChecked(244, true);
        if (boxcheck245) mercmissionsLayout.setItemChecked(245, true);
        if (boxcheck246) mercmissionsLayout.setItemChecked(246, true);
        if (boxcheck247) mercmissionsLayout.setItemChecked(247, true);
        if (boxcheck248) mercmissionsLayout.setItemChecked(248, true);
        if (boxcheck249) mercmissionsLayout.setItemChecked(249, true);
        if (boxcheck250) mercmissionsLayout.setItemChecked(250, true);
        if (boxcheck251) mercmissionsLayout.setItemChecked(251, true);
        if (boxcheck252) mercmissionsLayout.setItemChecked(252, true);
        if (boxcheck253) mercmissionsLayout.setItemChecked(253, true);
        if (boxcheck254) mercmissionsLayout.setItemChecked(254, true);
        if (boxcheck255) mercmissionsLayout.setItemChecked(255, true);
        if (boxcheck256) mercmissionsLayout.setItemChecked(256, true);
        if (boxcheck257) mercmissionsLayout.setItemChecked(257, true);
        if (boxcheck258) mercmissionsLayout.setItemChecked(258, true);
        if (boxcheck259) mercmissionsLayout.setItemChecked(259, true);
        if (boxcheck260) mercmissionsLayout.setItemChecked(260, true);
        if (boxcheck261) mercmissionsLayout.setItemChecked(261, true);
        if (boxcheck262) mercmissionsLayout.setItemChecked(262, true);
        if (boxcheck263) mercmissionsLayout.setItemChecked(263, true);
        if (boxcheck264) mercmissionsLayout.setItemChecked(264, true);
        if (boxcheck265) mercmissionsLayout.setItemChecked(265, true);
        if (boxcheck266) mercmissionsLayout.setItemChecked(266, true);
        if (boxcheck267) mercmissionsLayout.setItemChecked(267, true);
        if (boxcheck268) mercmissionsLayout.setItemChecked(268, true);
        if (boxcheck269) mercmissionsLayout.setItemChecked(269, true);
        if (boxcheck270) mercmissionsLayout.setItemChecked(270, true);
        if (boxcheck271) mercmissionsLayout.setItemChecked(271, true);
        if (boxcheck272) mercmissionsLayout.setItemChecked(272, true);
        if (boxcheck273) mercmissionsLayout.setItemChecked(273, true);
        if (boxcheck274) mercmissionsLayout.setItemChecked(274, true);
        if (boxcheck275) mercmissionsLayout.setItemChecked(275, true);
        if (boxcheck276) mercmissionsLayout.setItemChecked(276, true);
        if (boxcheck277) mercmissionsLayout.setItemChecked(277, true);
        if (boxcheck278) mercmissionsLayout.setItemChecked(278, true);
        if (boxcheck279) mercmissionsLayout.setItemChecked(279, true);
        if (boxcheck280) mercmissionsLayout.setItemChecked(280, true);
        if (boxcheck281) mercmissionsLayout.setItemChecked(281, true);
        if (boxcheck282) mercmissionsLayout.setItemChecked(282, true);
        if (boxcheck283) mercmissionsLayout.setItemChecked(283, true);
        if (boxcheck284) mercmissionsLayout.setItemChecked(284, true);
        if (boxcheck285) mercmissionsLayout.setItemChecked(285, true);
        if (boxcheck286) mercmissionsLayout.setItemChecked(286, true);
        if (boxcheck287) mercmissionsLayout.setItemChecked(287, true);
        if (boxcheck288) mercmissionsLayout.setItemChecked(288, true);
        if (boxcheck289) mercmissionsLayout.setItemChecked(289, true);
        if (boxcheck290) mercmissionsLayout.setItemChecked(290, true);
        if (boxcheck291) mercmissionsLayout.setItemChecked(291, true);
        if (boxcheck292) mercmissionsLayout.setItemChecked(292, true);
        if (boxcheck293) mercmissionsLayout.setItemChecked(293, true);
        if (boxcheck294) mercmissionsLayout.setItemChecked(294, true);
        if (boxcheck295) mercmissionsLayout.setItemChecked(295, true);
        if (boxcheck296) mercmissionsLayout.setItemChecked(296, true);
        if (boxcheck297) mercmissionsLayout.setItemChecked(297, true);
        if (boxcheck298) mercmissionsLayout.setItemChecked(298, true);
        return;

    }

}
